// Code generated by gowsdl DO NOT EDIT.

package wgestabref

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type ListaDescripcion struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaDescripcion"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ListaDescripcionResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaDescripcionResponse"`

	ListaDescripcionResult *Descripciones `xml:"ListaDescripcionResult,omitempty" json:"ListaDescripcionResult,omitempty"`
}

type ListaVigencias struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaVigencias"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ListaVigenciasResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaVigenciasResponse"`

	ListaVigenciasResult *Vigencias `xml:"ListaVigenciasResult,omitempty" json:"ListaVigenciasResult,omitempty"`
}

type DocumentosVigentes struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef DocumentosVigentes"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`
}

type DocumentosVigentesResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef DocumentosVigentesResponse"`

	DocumentosVigentesResult *VigenciasIndicador `xml:"DocumentosVigentesResult,omitempty" json:"DocumentosVigentesResult,omitempty"`
}

type ListaPaisesAduanas struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaPaisesAduanas"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ListaPaisesAduanasResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaPaisesAduanasResponse"`

	ListaPaisesAduanasResult *PaisesAduanas `xml:"ListaPaisesAduanasResult,omitempty" json:"ListaPaisesAduanasResult,omitempty"`
}

type ListaEmpresas struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaEmpresas"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ListaEmpresasResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaEmpresasResponse"`

	ListaEmpresasResult *Empresas `xml:"ListaEmpresasResult,omitempty" json:"ListaEmpresasResult,omitempty"`
}

type ListaArancel struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaArancel"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ListaArancelResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaArancelResponse"`

	ListaArancelResult *Opciones `xml:"ListaArancelResult,omitempty" json:"ListaArancelResult,omitempty"`
}

type ListaLugaresOperativos struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaLugaresOperativos"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ListaLugaresOperativosResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaLugaresOperativosResponse"`

	ListaLugaresOperativosResult *LugaresOperativos `xml:"ListaLugaresOperativosResult,omitempty" json:"ListaLugaresOperativosResult,omitempty"`
}

type ListaTablasReferencia struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaTablasReferencia"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`
}

type ListaTablasReferenciaResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaTablasReferenciaResponse"`

	ListaTablasReferenciaResult *TablasReferencia `xml:"ListaTablasReferenciaResult,omitempty" json:"ListaTablasReferenciaResult,omitempty"`
}

type ListaTablasReferenciaServicio struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaTablasReferenciaServicio"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdServicio string `xml:"IdServicio,omitempty" json:"IdServicio,omitempty"`
}

type ListaTablasReferenciaServicioResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaTablasReferenciaServicioResponse"`

	ListaTablasReferenciaServicioResult *TablasReferencia `xml:"ListaTablasReferenciaServicioResult,omitempty" json:"ListaTablasReferenciaServicioResult,omitempty"`
}

type ListaDescripcionDecodificacion struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaDescripcionDecodificacion"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ListaDescripcionDecodificacionResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaDescripcionDecodificacionResponse"`

	ListaDescripcionDecodificacionResult *DescripcionesCodificaciones `xml:"ListaDescripcionDecodificacionResult,omitempty" json:"ListaDescripcionDecodificacionResult,omitempty"`
}

type ListaDatoComplementario struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaDatoComplementario"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ListaDatoComplementarioResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ListaDatoComplementarioResponse"`

	ListaDatoComplementarioResult *DatosComplementarios `xml:"ListaDatoComplementarioResult,omitempty" json:"ListaDatoComplementarioResult,omitempty"`
}

type ConsultarFechaUltAct struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ConsultarFechaUltAct"`

	Autentica *Autenticacion `xml:"Autentica,omitempty" json:"Autentica,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type ConsultarFechaUltActResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef ConsultarFechaUltActResponse"`

	ConsultarFechaUltActResult *FechaUltAct `xml:"ConsultarFechaUltActResult,omitempty" json:"ConsultarFechaUltActResult,omitempty"`
}

type Dummy struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef Dummy"`
}

type DummyResponse struct {
	XMLName xml.Name `xml:"ar.gov.afip.dia.serviciosweb.wgesTabRef DummyResponse"`

	DummyResult *WsDummyResponse `xml:"DummyResult,omitempty" json:"DummyResult,omitempty"`
}

type Autenticacion struct {
	Cuit string `xml:"Cuit,omitempty" json:"Cuit,omitempty"`

	TipoAgente string `xml:"TipoAgente,omitempty" json:"TipoAgente,omitempty"`

	Rol string `xml:"Rol,omitempty" json:"Rol,omitempty"`

	Token *string `xml:"Token,omitempty" json:"Token,omitempty"`

	Sign *string `xml:"Sign,omitempty" json:"Sign,omitempty"`
}

type Descripciones struct {
	*Contenedor

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`

	Descripciones *ArrayOfDescripcion `xml:"Descripciones,omitempty" json:"Descripciones,omitempty"`
}

type Contenedor struct {
	CodError int32 `xml:"CodError,omitempty" json:"CodError,omitempty"`

	InfoAdicional string `xml:"InfoAdicional,omitempty" json:"InfoAdicional,omitempty"`
}

type ArrayOfDescripcion struct {
	Descripcion []*Descripcion `xml:"Descripcion,omitempty" json:"Descripcion,omitempty"`
}

type Descripcion struct {
	Codigo string `xml:"Codigo,omitempty" json:"Codigo,omitempty"`

	Descripcion string `xml:"Descripcion,omitempty" json:"Descripcion,omitempty"`
}

type Vigencias struct {
	*Contenedor

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`

	Vigencias *ArrayOfVigencia `xml:"Vigencias,omitempty" json:"Vigencias,omitempty"`
}

type ArrayOfVigencia struct {
	Vigencia []*Vigencia `xml:"Vigencia,omitempty" json:"Vigencia,omitempty"`
}

type Vigencia struct {
	*Descripcion

	VigenciaDesde string `xml:"VigenciaDesde,omitempty" json:"VigenciaDesde,omitempty"`

	VigenciaHasta string `xml:"VigenciaHasta,omitempty" json:"VigenciaHasta,omitempty"`
}

type VigenciasIndicador struct {
	*Contenedor

	VigenciasIndicador *ArrayOfVigenciaIndicador `xml:"VigenciasIndicador,omitempty" json:"VigenciasIndicador,omitempty"`
}

type ArrayOfVigenciaIndicador struct {
	VigenciaIndicador []*VigenciaIndicador `xml:"VigenciaIndicador,omitempty" json:"VigenciaIndicador,omitempty"`
}

type VigenciaIndicador struct {
	*Vigencia

	Indicador string `xml:"Indicador,omitempty" json:"Indicador,omitempty"`
}

type PaisesAduanas struct {
	*Contenedor

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`

	PaisesAduanas *ArrayOfPaisAduana `xml:"PaisesAduanas,omitempty" json:"PaisesAduanas,omitempty"`
}

type ArrayOfPaisAduana struct {
	PaisAduana []*PaisAduana `xml:"PaisAduana,omitempty" json:"PaisAduana,omitempty"`
}

type PaisAduana struct {
	*Vigencia

	Pais string `xml:"Pais,omitempty" json:"Pais,omitempty"`

	Aduana string `xml:"Aduana,omitempty" json:"Aduana,omitempty"`
}

type Empresas struct {
	*Contenedor

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`

	Empresas *ArrayOfEmpresa `xml:"Empresas,omitempty" json:"Empresas,omitempty"`
}

type ArrayOfEmpresa struct {
	Empresa []*Empresa `xml:"Empresa,omitempty" json:"Empresa,omitempty"`
}

type Empresa struct {
	Cuit string `xml:"Cuit,omitempty" json:"Cuit,omitempty"`

	RazonSocial string `xml:"RazonSocial,omitempty" json:"RazonSocial,omitempty"`
}

type Opciones struct {
	*Contenedor

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`

	Opciones *ArrayOfOpcion `xml:"Opciones,omitempty" json:"Opciones,omitempty"`
}

type ArrayOfOpcion struct {
	Opcion []*Opcion `xml:"Opcion,omitempty" json:"Opcion,omitempty"`
}

type Opcion struct {
	*Vigencia

	Opcion string `xml:"Opcion,omitempty" json:"Opcion,omitempty"`
}

type LugaresOperativos struct {
	*Contenedor

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`

	LugaresOperativos *ArrayOfLugarOperativo `xml:"LugaresOperativos,omitempty" json:"LugaresOperativos,omitempty"`
}

type ArrayOfLugarOperativo struct {
	LugarOperativo []*LugarOperativo `xml:"LugarOperativo,omitempty" json:"LugarOperativo,omitempty"`
}

type LugarOperativo struct {
	*Vigencia

	Aduana string `xml:"Aduana,omitempty" json:"Aduana,omitempty"`

	LugarOperativo string `xml:"LugarOperativo,omitempty" json:"LugarOperativo,omitempty"`
}

type TablasReferencia struct {
	*Contenedor

	TablasReferencia *ArrayOfTablaReferencia `xml:"TablasReferencia,omitempty" json:"TablasReferencia,omitempty"`
}

type ArrayOfTablaReferencia struct {
	TablaReferencia []*TablaReferencia `xml:"TablaReferencia,omitempty" json:"TablaReferencia,omitempty"`
}

type TablaReferencia struct {
	IdTabRef string `xml:"IdTabRef,omitempty" json:"IdTabRef,omitempty"`

	TabRefDesc string `xml:"TabRefDesc,omitempty" json:"TabRefDesc,omitempty"`

	WebMethod string `xml:"WebMethod,omitempty" json:"WebMethod,omitempty"`
}

type DescripcionesCodificaciones struct {
	*Contenedor

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`

	DescripcionesCodificaciones *ArrayOfDescripcionCodificacion `xml:"DescripcionesCodificaciones,omitempty" json:"DescripcionesCodificaciones,omitempty"`
}

type ArrayOfDescripcionCodificacion struct {
	DescripcionCodificacion []*DescripcionCodificacion `xml:"DescripcionCodificacion,omitempty" json:"DescripcionCodificacion,omitempty"`
}

type DescripcionCodificacion struct {
	*Descripcion

	CodigoIso string `xml:"CodigoIso,omitempty" json:"CodigoIso,omitempty"`
}

type DatosComplementarios struct {
	*Contenedor

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`

	DatosComplementarios *ArrayOfDatoComplementario `xml:"DatosComplementarios,omitempty" json:"DatosComplementarios,omitempty"`
}

type ArrayOfDatoComplementario struct {
	DatoComplementario []*DatoComplementario `xml:"DatoComplementario,omitempty" json:"DatoComplementario,omitempty"`
}

type DatoComplementario struct {
	*VigenciaIndicador

	Formato string `xml:"Formato,omitempty" json:"Formato,omitempty"`
}

type FechaUltAct struct {
	*Contenedor

	Fecha soap.XSDDateTime `xml:"Fecha,omitempty" json:"Fecha,omitempty"`

	IdReferencia string `xml:"IdReferencia,omitempty" json:"IdReferencia,omitempty"`
}

type WsDummyResponse struct {
	Appserver string `xml:"appserver,omitempty" json:"appserver,omitempty"`

	Dbserver string `xml:"dbserver,omitempty" json:"dbserver,omitempty"`

	Authserver string `xml:"authserver,omitempty" json:"authserver,omitempty"`
}

type WgesTabRefSoap interface {

	/* Emite tabla del tipo codigo/descripcion. */
	ListaDescripcion(request *ListaDescripcion) (*ListaDescripcionResponse, error)

	ListaDescripcionContext(ctx context.Context, request *ListaDescripcion) (*ListaDescripcionResponse, error)

	/* Emite tabla del tipo codigo/descripcion/vigencia. */
	ListaVigencias(request *ListaVigencias) (*ListaVigenciasResponse, error)

	ListaVigenciasContext(ctx context.Context, request *ListaVigencias) (*ListaVigenciasResponse, error)

	/* Emite tabla del tipo codigo/descripcion/vigencia. */
	DocumentosVigentes(request *DocumentosVigentes) (*DocumentosVigentesResponse, error)

	DocumentosVigentesContext(ctx context.Context, request *DocumentosVigentes) (*DocumentosVigentesResponse, error)

	/* Emite tabla del tipo codigo/descripcion/vigencia/pais o aduana. */
	ListaPaisesAduanas(request *ListaPaisesAduanas) (*ListaPaisesAduanasResponse, error)

	ListaPaisesAduanasContext(ctx context.Context, request *ListaPaisesAduanas) (*ListaPaisesAduanasResponse, error)

	/* Emite tabla del tipo cuit/razon social. */
	ListaEmpresas(request *ListaEmpresas) (*ListaEmpresasResponse, error)

	ListaEmpresasContext(ctx context.Context, request *ListaEmpresas) (*ListaEmpresasResponse, error)

	/* Emite tabla del tipo codigo/descripcion/Opcion/vigencia. */
	ListaArancel(request *ListaArancel) (*ListaArancelResponse, error)

	ListaArancelContext(ctx context.Context, request *ListaArancel) (*ListaArancelResponse, error)

	/* Emite tabla del tipo codigo/descripcion/vigencia/aduana/lugar operativo. */
	ListaLugaresOperativos(request *ListaLugaresOperativos) (*ListaLugaresOperativosResponse, error)

	ListaLugaresOperativosContext(ctx context.Context, request *ListaLugaresOperativos) (*ListaLugaresOperativosResponse, error)

	/* Emite tabla del tipo: Tabla de Referencia, Descripcion Tabla Referencia, WebMethod que se debe utilizar para obtener los datos de dicha tabla. */
	ListaTablasReferencia(request *ListaTablasReferencia) (*ListaTablasReferenciaResponse, error)

	ListaTablasReferenciaContext(ctx context.Context, request *ListaTablasReferencia) (*ListaTablasReferenciaResponse, error)

	/* Para un Id de Servicio, emite tabla del tipo: Tabla de Referencia, Descripcion Tabla Referencia, WebMethod que se debe utilizar para obtener los datos de dicha tabla. */
	ListaTablasReferenciaServicio(request *ListaTablasReferenciaServicio) (*ListaTablasReferenciaServicioResponse, error)

	ListaTablasReferenciaServicioContext(ctx context.Context, request *ListaTablasReferenciaServicio) (*ListaTablasReferenciaServicioResponse, error)

	/* Emite tabla del tipo codigo/descripcion/codificacion. */
	ListaDescripcionDecodificacion(request *ListaDescripcionDecodificacion) (*ListaDescripcionDecodificacionResponse, error)

	ListaDescripcionDecodificacionContext(ctx context.Context, request *ListaDescripcionDecodificacion) (*ListaDescripcionDecodificacionResponse, error)

	/* Emite tabla del tipo codigo/descripcion/vigencia/indicador/formato. */
	ListaDatoComplementario(request *ListaDatoComplementario) (*ListaDatoComplementarioResponse, error)

	ListaDatoComplementarioContext(ctx context.Context, request *ListaDatoComplementario) (*ListaDatoComplementarioResponse, error)

	/* Retorna la fecha de última actualización de la tabla consultada. */
	ConsultarFechaUltAct(request *ConsultarFechaUltAct) (*ConsultarFechaUltActResponse, error)

	ConsultarFechaUltActContext(ctx context.Context, request *ConsultarFechaUltAct) (*ConsultarFechaUltActResponse, error)

	/* Metodo dummy para verificacion de funcionamiento */
	Dummy(request *Dummy) (*DummyResponse, error)

	DummyContext(ctx context.Context, request *Dummy) (*DummyResponse, error)
}

type wgesTabRefSoap struct {
	client *soap.Client
}

func NewWgesTabRefSoap(client *soap.Client) WgesTabRefSoap {
	return &wgesTabRefSoap{
		client: client,
	}
}

func (service *wgesTabRefSoap) ListaDescripcionContext(ctx context.Context, request *ListaDescripcion) (*ListaDescripcionResponse, error) {
	response := new(ListaDescripcionResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaDescripcion", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaDescripcion(request *ListaDescripcion) (*ListaDescripcionResponse, error) {
	return service.ListaDescripcionContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaVigenciasContext(ctx context.Context, request *ListaVigencias) (*ListaVigenciasResponse, error) {
	response := new(ListaVigenciasResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaVigencias", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaVigencias(request *ListaVigencias) (*ListaVigenciasResponse, error) {
	return service.ListaVigenciasContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) DocumentosVigentesContext(ctx context.Context, request *DocumentosVigentes) (*DocumentosVigentesResponse, error) {
	response := new(DocumentosVigentesResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/DocumentosVigentes", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) DocumentosVigentes(request *DocumentosVigentes) (*DocumentosVigentesResponse, error) {
	return service.DocumentosVigentesContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaPaisesAduanasContext(ctx context.Context, request *ListaPaisesAduanas) (*ListaPaisesAduanasResponse, error) {
	response := new(ListaPaisesAduanasResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaPaisesAduanas", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaPaisesAduanas(request *ListaPaisesAduanas) (*ListaPaisesAduanasResponse, error) {
	return service.ListaPaisesAduanasContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaEmpresasContext(ctx context.Context, request *ListaEmpresas) (*ListaEmpresasResponse, error) {
	response := new(ListaEmpresasResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaEmpresas", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaEmpresas(request *ListaEmpresas) (*ListaEmpresasResponse, error) {
	return service.ListaEmpresasContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaArancelContext(ctx context.Context, request *ListaArancel) (*ListaArancelResponse, error) {
	response := new(ListaArancelResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaArancel", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaArancel(request *ListaArancel) (*ListaArancelResponse, error) {
	return service.ListaArancelContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaLugaresOperativosContext(ctx context.Context, request *ListaLugaresOperativos) (*ListaLugaresOperativosResponse, error) {
	response := new(ListaLugaresOperativosResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaLugaresOperativos", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaLugaresOperativos(request *ListaLugaresOperativos) (*ListaLugaresOperativosResponse, error) {
	return service.ListaLugaresOperativosContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaTablasReferenciaContext(ctx context.Context, request *ListaTablasReferencia) (*ListaTablasReferenciaResponse, error) {
	response := new(ListaTablasReferenciaResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaTablasReferencia", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaTablasReferencia(request *ListaTablasReferencia) (*ListaTablasReferenciaResponse, error) {
	return service.ListaTablasReferenciaContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaTablasReferenciaServicioContext(ctx context.Context, request *ListaTablasReferenciaServicio) (*ListaTablasReferenciaServicioResponse, error) {
	response := new(ListaTablasReferenciaServicioResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaTablasReferenciaServicio", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaTablasReferenciaServicio(request *ListaTablasReferenciaServicio) (*ListaTablasReferenciaServicioResponse, error) {
	return service.ListaTablasReferenciaServicioContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaDescripcionDecodificacionContext(ctx context.Context, request *ListaDescripcionDecodificacion) (*ListaDescripcionDecodificacionResponse, error) {
	response := new(ListaDescripcionDecodificacionResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaDescripcionDecodificacion", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaDescripcionDecodificacion(request *ListaDescripcionDecodificacion) (*ListaDescripcionDecodificacionResponse, error) {
	return service.ListaDescripcionDecodificacionContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ListaDatoComplementarioContext(ctx context.Context, request *ListaDatoComplementario) (*ListaDatoComplementarioResponse, error) {
	response := new(ListaDatoComplementarioResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ListaDatoComplementario", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ListaDatoComplementario(request *ListaDatoComplementario) (*ListaDatoComplementarioResponse, error) {
	return service.ListaDatoComplementarioContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) ConsultarFechaUltActContext(ctx context.Context, request *ConsultarFechaUltAct) (*ConsultarFechaUltActResponse, error) {
	response := new(ConsultarFechaUltActResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/ConsultarFechaUltAct", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) ConsultarFechaUltAct(request *ConsultarFechaUltAct) (*ConsultarFechaUltActResponse, error) {
	return service.ConsultarFechaUltActContext(
		context.Background(),
		request,
	)
}

func (service *wgesTabRefSoap) DummyContext(ctx context.Context, request *Dummy) (*DummyResponse, error) {
	response := new(DummyResponse)
	err := service.client.CallContext(ctx, "ar.gov.afip.dia.serviciosweb.wgesTabRef/Dummy", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgesTabRefSoap) Dummy(request *Dummy) (*DummyResponse, error) {
	return service.DummyContext(
		context.Background(),
		request,
	)
}
