// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Sebastian Hogas",
            "email": "sehogas@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/anular-caratula": {
            "delete": {
                "description": "Anular Carátula sin COEMs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnularCaratula"
                ],
                "summary": "Anular Carátula",
                "parameters": [
                    {
                        "description": "AnularCaratulaRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.IdentificadorCaraturaParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/anular-coem": {
            "delete": {
                "description": "Anular COEM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AnularCOEM"
                ],
                "summary": "Anular COEM",
                "parameters": [
                    {
                        "description": "AnularCOEMRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.IdentificadorCOEMParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cerrar-coem": {
            "post": {
                "description": "Cerrar COEM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CerrarCOEM"
                ],
                "summary": "Cerrar COEM",
                "parameters": [
                    {
                        "description": "CerrarCOEMRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.IdentificadorCOEMParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dummy": {
            "get": {
                "description": "Visualizar el estado del servicio web, del servicio de autenticación y de la base de datos de ARCA",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dummy"
                ],
                "summary": "Muestra el estado del servicio",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DummyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rectificar-caratula": {
            "put": {
                "description": "Rectificar una Carátula sin COEMs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RectificarCaratula"
                ],
                "summary": "Rectificar Carátula",
                "parameters": [
                    {
                        "description": "RectificarCaratulaRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.RectificarCaratulaParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rectificar-coem": {
            "put": {
                "description": "Rectificar COEM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RectificarCOEM"
                ],
                "summary": "Rectificar COEM",
                "parameters": [
                    {
                        "description": "RectificarCOEMRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.RectificarCOEMParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/registrar-caratula": {
            "post": {
                "description": "Registra una nueva Carátula",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RegistrarCaratula"
                ],
                "summary": "Registrar Carátula",
                "parameters": [
                    {
                        "description": "RegistrarCaratulaRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.CaratulaParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/registrar-coem": {
            "post": {
                "description": "Registrar COEM en Carátula",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RegistrarCOEM"
                ],
                "summary": "Registrar COEM",
                "parameters": [
                    {
                        "description": "RegistrarCOEMRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.RegistrarCOEMParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/solicitar-anulacion-coem": {
            "post": {
                "description": "Solicitar anulación COEM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SolicitarAnulacionCOEM"
                ],
                "summary": "Solicitar Anulación COEM",
                "parameters": [
                    {
                        "description": "SolicitarAnulacionCOEMRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.IdentificadorCOEMParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/solicitar-cambio-buque": {
            "put": {
                "description": "Solicitar cambio de Buque para Carátulas con COEMs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SolicitarCambioBuque"
                ],
                "summary": "Solicitar cambio de Buque",
                "parameters": [
                    {
                        "description": "SolicitarCambioBuqueRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.CambioBuqueParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/solicitar-cambio-fechas": {
            "put": {
                "description": "Solicitar cambio de Fechas para Carátulas con COEMs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SolicitarCambioFechas"
                ],
                "summary": "Solicitar cambio de Fechas",
                "parameters": [
                    {
                        "description": "CambioFechasParamsRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.CambioFechasParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/solicitar-cambio-lot": {
            "put": {
                "description": "Solicitar cambio de Lugar Operativo para Carátulas con COEMs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SolicitarCambioLOT"
                ],
                "summary": "Solicitar cambio de LOT",
                "parameters": [
                    {
                        "description": "CambioLOTParamsRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.CambioLOTParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/solicitar-cierre-carga-conto-bulto": {
            "post": {
                "description": "Solicitar Cierre de Carga Contenedores y/o Bultos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SolicitarCierreCargaContoBulto"
                ],
                "summary": "Solicitar Cierre de Carga Contenedores y/o Bultos",
                "parameters": [
                    {
                        "description": "SolicitarCierreCargaContoBultoRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.SolicitarCierreCargaContoBultoParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/solicitar-cierre-carga-granel": {
            "post": {
                "description": "Solicitar Cierre de Carga Granel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SolicitarCierreCargaGranel"
                ],
                "summary": "Solicitar Cierre de Carga Granel",
                "parameters": [
                    {
                        "description": "SolicitarCierreCargaGranel",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.SolicitarCierreCargaGranelParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/solicitar-no-abordo": {
            "post": {
                "description": "Solicitar No Abordo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SolicitarNoABordo"
                ],
                "summary": "Solicitar No Abordo",
                "parameters": [
                    {
                        "description": "SolicitarNoABordoRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/afip.IdentificadorCOEMParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "afip.CambioBuqueParams": {
            "type": "object",
            "required": [
                "IdentificadorCaratula"
            ],
            "properties": {
                "IdentificadorBuque": {
                    "type": "string",
                    "maxLength": 20
                },
                "IdentificadorCaratula": {
                    "type": "string"
                },
                "NombreMedioTransporte": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "afip.CambioFechasParams": {
            "type": "object",
            "required": [
                "CodigoMotivo",
                "FechaArribo",
                "FechaZarpada",
                "IdentificadorCaratula"
            ],
            "properties": {
                "CodigoMotivo": {
                    "type": "string",
                    "maxLength": 2
                },
                "DescripcionMotivo": {
                    "type": "string",
                    "maxLength": 200
                },
                "FechaArribo": {
                    "type": "string"
                },
                "FechaZarpada": {
                    "type": "string"
                },
                "IdentificadorCaratula": {
                    "type": "string"
                }
            }
        },
        "afip.CambioLOTParams": {
            "type": "object",
            "required": [
                "CodigoLugarOperativo",
                "IdentificadorCaratula"
            ],
            "properties": {
                "CodigoLugarOperativo": {
                    "type": "string",
                    "maxLength": 5
                },
                "IdentificadorCaratula": {
                    "type": "string"
                }
            }
        },
        "afip.CaratulaParams": {
            "type": "object",
            "required": [
                "CodigoAduana",
                "CodigoLugarOperativo",
                "FechaArribo",
                "FechaZarpada",
                "NombreMedioTransporte",
                "Via"
            ],
            "properties": {
                "CodigoAduana": {
                    "type": "string"
                },
                "CodigoLugarOperativo": {
                    "type": "string"
                },
                "FechaArribo": {
                    "type": "string"
                },
                "FechaZarpada": {
                    "type": "string"
                },
                "IdentificadorBuque": {
                    "type": "string",
                    "maxLength": 20
                },
                "Itinerario": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.PuertoDestinoParams"
                    }
                },
                "NombreMedioTransporte": {
                    "type": "string",
                    "maxLength": 200
                },
                "NumeroViaje": {
                    "type": "string",
                    "maxLength": 16
                },
                "PuertoDestino": {
                    "type": "string"
                },
                "Via": {
                    "type": "string"
                }
            }
        },
        "afip.ContenedorCarga": {
            "type": "object",
            "required": [
                "IdentificadorContenedor"
            ],
            "properties": {
                "CuitATA": {
                    "type": "string"
                },
                "Declaraciones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "IdentificadorContenedor": {
                    "type": "string"
                },
                "Peso": {
                    "type": "number"
                },
                "Precintos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "Tipo": {
                    "type": "string"
                }
            }
        },
        "afip.ContenedorVacio": {
            "type": "object",
            "required": [
                "IdentificadorContenedor"
            ],
            "properties": {
                "CodigoPais": {
                    "type": "string"
                },
                "CuitATA": {
                    "type": "string"
                },
                "IdentificadorContenedor": {
                    "type": "string"
                },
                "Tipo": {
                    "type": "string"
                }
            }
        },
        "afip.DeclaracionCOEMGranel": {
            "type": "object",
            "properties": {
                "DeclaracionesGranel": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.DeclaracionGranel"
                    }
                },
                "IdentificadorCOEM": {
                    "type": "string"
                }
            }
        },
        "afip.DeclaracionCont": {
            "type": "object",
            "properties": {
                "FechaEmbarque": {
                    "type": "string"
                },
                "IdentificadorDeclaracion": {
                    "type": "string"
                }
            }
        },
        "afip.DeclaracionGranel": {
            "type": "object",
            "properties": {
                "FechaEmbarque": {
                    "type": "string"
                },
                "IdentificadorCierreCumplido": {
                    "type": "string"
                },
                "IdentificadorDeclaracion": {
                    "type": "string"
                },
                "Items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.ItemGranel"
                    }
                }
            }
        },
        "afip.Embalaje": {
            "type": "object",
            "properties": {
                "CantidadBultos": {
                    "type": "integer"
                },
                "CodigoEmbalaje": {
                    "type": "string"
                },
                "Peso": {
                    "type": "number"
                }
            }
        },
        "afip.IdentificadorCOEMParams": {
            "type": "object",
            "required": [
                "IdentificadorCOEM",
                "IdentificadorCaratula"
            ],
            "properties": {
                "IdentificadorCOEM": {
                    "type": "string"
                },
                "IdentificadorCaratula": {
                    "type": "string"
                }
            }
        },
        "afip.IdentificadorCaraturaParams": {
            "type": "object",
            "required": [
                "IdentificadorCaratula"
            ],
            "properties": {
                "IdentificadorCaratula": {
                    "type": "string"
                }
            }
        },
        "afip.ItemGranel": {
            "type": "object",
            "properties": {
                "CantidadReal": {
                    "type": "number"
                },
                "NumeroItem": {
                    "type": "integer"
                }
            }
        },
        "afip.MercaderiaSuelta": {
            "type": "object",
            "properties": {
                "CuitATA": {
                    "type": "string"
                },
                "Embalajes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.Embalaje"
                    }
                },
                "IdentificadorDeclaracion": {
                    "type": "string"
                }
            }
        },
        "afip.PuertoDestinoParams": {
            "type": "object",
            "properties": {
                "PuertoDestino": {
                    "type": "string"
                }
            }
        },
        "afip.RectificarCOEMParams": {
            "type": "object",
            "required": [
                "IdentificadorCOEM",
                "IdentificadorCaratula"
            ],
            "properties": {
                "ContenedoresConCarga": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.ContenedorCarga"
                    }
                },
                "ContenedoresVacios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.ContenedorVacio"
                    }
                },
                "IdentificadorCOEM": {
                    "type": "string"
                },
                "IdentificadorCaratula": {
                    "type": "string"
                },
                "MercaderiasSueltas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.MercaderiaSuelta"
                    }
                }
            }
        },
        "afip.RectificarCaratulaParams": {
            "type": "object",
            "required": [
                "CodigoAduana",
                "CodigoLugarOperativo",
                "FechaArribo",
                "FechaZarpada",
                "IdentificadorCaratula",
                "NombreMedioTransporte",
                "Via"
            ],
            "properties": {
                "CodigoAduana": {
                    "type": "string"
                },
                "CodigoLugarOperativo": {
                    "type": "string"
                },
                "FechaArribo": {
                    "type": "string"
                },
                "FechaZarpada": {
                    "type": "string"
                },
                "IdentificadorBuque": {
                    "type": "string",
                    "maxLength": 20
                },
                "IdentificadorCaratula": {
                    "type": "string"
                },
                "Itinerario": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.PuertoDestinoParams"
                    }
                },
                "NombreMedioTransporte": {
                    "type": "string",
                    "maxLength": 200
                },
                "NumeroViaje": {
                    "type": "string",
                    "maxLength": 16
                },
                "PuertoDestino": {
                    "type": "string"
                },
                "Via": {
                    "type": "string"
                }
            }
        },
        "afip.RegistrarCOEMParams": {
            "type": "object",
            "required": [
                "IdentificadorCaratula"
            ],
            "properties": {
                "ContenedoresConCarga": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.ContenedorCarga"
                    }
                },
                "ContenedoresVacios": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.ContenedorVacio"
                    }
                },
                "IdentificadorCaratula": {
                    "type": "string"
                },
                "MercaderiasSueltas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.MercaderiaSuelta"
                    }
                }
            }
        },
        "afip.SolicitarCierreCargaContoBultoParams": {
            "type": "object",
            "required": [
                "FechaZarpada",
                "IdentificadorCaratula"
            ],
            "properties": {
                "Declaraciones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.DeclaracionCont"
                    }
                },
                "FechaZarpada": {
                    "type": "string"
                },
                "IdentificadorCaratula": {
                    "type": "string"
                },
                "NumeroViaje": {
                    "type": "string"
                }
            }
        },
        "afip.SolicitarCierreCargaGranelParams": {
            "type": "object",
            "required": [
                "FechaZarpada",
                "IdentificadorCaratula"
            ],
            "properties": {
                "DeclaracionesCOEMGranel": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/afip.DeclaracionCOEMGranel"
                    }
                },
                "FechaZarpada": {
                    "type": "string"
                },
                "IdentificadorCaratula": {
                    "type": "string"
                },
                "NumeroViaje": {
                    "type": "string"
                }
            }
        },
        "dto.DummyResponse": {
            "type": "object",
            "properties": {
                "AppServer": {
                    "type": "string"
                },
                "AuthServer": {
                    "type": "string"
                },
                "DbServer": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ARCA - Comunicación de Embarque API",
	Description:      "Esta API Json RESTFul actua como proxy SOAP a los servicios de Comunicación de Embarque de ARCA.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
