// Code generated by gowsdl DO NOT EDIT.

package wsfe

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type FECAESolicitar struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAESolicitar"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	FeCAEReq *FECAERequest `xml:"FeCAEReq,omitempty" json:"FeCAEReq,omitempty"`
}

type FECAESolicitarResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAESolicitarResponse"`

	FECAESolicitarResult *FECAEResponse `xml:"FECAESolicitarResult,omitempty" json:"FECAESolicitarResult,omitempty"`
}

type FECompTotXRequest struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECompTotXRequest"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FECompTotXRequestResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECompTotXRequestResponse"`

	FECompTotXRequestResult *FERegXReqResponse `xml:"FECompTotXRequestResult,omitempty" json:"FECompTotXRequestResult,omitempty"`
}

type FEDummy struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEDummy"`
}

type FEDummyResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEDummyResponse"`

	FEDummyResult *DummyResponse `xml:"FEDummyResult,omitempty" json:"FEDummyResult,omitempty"`
}

type FECompUltimoAutorizado struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECompUltimoAutorizado"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`

	CbteTipo int32 `xml:"CbteTipo,omitempty" json:"CbteTipo,omitempty"`
}

type FECompUltimoAutorizadoResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECompUltimoAutorizadoResponse"`

	FECompUltimoAutorizadoResult *FERecuperaLastCbteResponse `xml:"FECompUltimoAutorizadoResult,omitempty" json:"FECompUltimoAutorizadoResult,omitempty"`
}

type FECompConsultar struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECompConsultar"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	FeCompConsReq *FECompConsultaReq `xml:"FeCompConsReq,omitempty" json:"FeCompConsReq,omitempty"`
}

type FECompConsultarResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECompConsultarResponse"`

	FECompConsultarResult *FECompConsultaResponse `xml:"FECompConsultarResult,omitempty" json:"FECompConsultarResult,omitempty"`
}

type FECAEARegInformativo struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEARegInformativo"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	FeCAEARegInfReq *FECAEARequest `xml:"FeCAEARegInfReq,omitempty" json:"FeCAEARegInfReq,omitempty"`
}

type FECAEARegInformativoResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEARegInformativoResponse"`

	FECAEARegInformativoResult *FECAEAResponse `xml:"FECAEARegInformativoResult,omitempty" json:"FECAEARegInformativoResult,omitempty"`
}

type FECAEASolicitar struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEASolicitar"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	Periodo int32 `xml:"Periodo,omitempty" json:"Periodo,omitempty"`

	Orden int16 `xml:"Orden,omitempty" json:"Orden,omitempty"`
}

type FECAEASolicitarResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEASolicitarResponse"`

	FECAEASolicitarResult *FECAEAGetResponse `xml:"FECAEASolicitarResult,omitempty" json:"FECAEASolicitarResult,omitempty"`
}

type FECAEASinMovimientoConsultar struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEASinMovimientoConsultar"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	CAEA string `xml:"CAEA,omitempty" json:"CAEA,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`
}

type FECAEASinMovimientoConsultarResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEASinMovimientoConsultarResponse"`

	FECAEASinMovimientoConsultarResult *FECAEASinMovConsResponse `xml:"FECAEASinMovimientoConsultarResult,omitempty" json:"FECAEASinMovimientoConsultarResult,omitempty"`
}

type FECAEASinMovimientoInformar struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEASinMovimientoInformar"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`

	CAEA string `xml:"CAEA,omitempty" json:"CAEA,omitempty"`
}

type FECAEASinMovimientoInformarResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEASinMovimientoInformarResponse"`

	FECAEASinMovimientoInformarResult *FECAEASinMovResponse `xml:"FECAEASinMovimientoInformarResult,omitempty" json:"FECAEASinMovimientoInformarResult,omitempty"`
}

type FECAEAConsultar struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEAConsultar"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	Periodo int32 `xml:"Periodo,omitempty" json:"Periodo,omitempty"`

	Orden int16 `xml:"Orden,omitempty" json:"Orden,omitempty"`
}

type FECAEAConsultarResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FECAEAConsultarResponse"`

	FECAEAConsultarResult *FECAEAGetResponse `xml:"FECAEAConsultarResult,omitempty" json:"FECAEAConsultarResult,omitempty"`
}

type FEParamGetCotizacion struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetCotizacion"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	MonId string `xml:"MonId,omitempty" json:"MonId,omitempty"`

	FchCotiz string `xml:"FchCotiz,omitempty" json:"FchCotiz,omitempty"`
}

type FEParamGetCotizacionResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetCotizacionResponse"`

	FEParamGetCotizacionResult *FECotizacionResponse `xml:"FEParamGetCotizacionResult,omitempty" json:"FEParamGetCotizacionResult,omitempty"`
}

type FEParamGetTiposTributos struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposTributos"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetTiposTributosResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposTributosResponse"`

	FEParamGetTiposTributosResult *FETributoResponse `xml:"FEParamGetTiposTributosResult,omitempty" json:"FEParamGetTiposTributosResult,omitempty"`
}

type FEParamGetTiposMonedas struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposMonedas"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetTiposMonedasResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposMonedasResponse"`

	FEParamGetTiposMonedasResult *MonedaResponse `xml:"FEParamGetTiposMonedasResult,omitempty" json:"FEParamGetTiposMonedasResult,omitempty"`
}

type FEParamGetTiposIva struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposIva"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetTiposIvaResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposIvaResponse"`

	FEParamGetTiposIvaResult *IvaTipoResponse `xml:"FEParamGetTiposIvaResult,omitempty" json:"FEParamGetTiposIvaResult,omitempty"`
}

type FEParamGetTiposOpcional struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposOpcional"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetTiposOpcionalResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposOpcionalResponse"`

	FEParamGetTiposOpcionalResult *OpcionalTipoResponse `xml:"FEParamGetTiposOpcionalResult,omitempty" json:"FEParamGetTiposOpcionalResult,omitempty"`
}

type FEParamGetTiposConcepto struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposConcepto"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetTiposConceptoResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposConceptoResponse"`

	FEParamGetTiposConceptoResult *ConceptoTipoResponse `xml:"FEParamGetTiposConceptoResult,omitempty" json:"FEParamGetTiposConceptoResult,omitempty"`
}

type FEParamGetPtosVenta struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetPtosVenta"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetPtosVentaResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetPtosVentaResponse"`

	FEParamGetPtosVentaResult *FEPtoVentaResponse `xml:"FEParamGetPtosVentaResult,omitempty" json:"FEParamGetPtosVentaResult,omitempty"`
}

type FEParamGetTiposCbte struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposCbte"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetTiposCbteResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposCbteResponse"`

	FEParamGetTiposCbteResult *CbteTipoResponse `xml:"FEParamGetTiposCbteResult,omitempty" json:"FEParamGetTiposCbteResult,omitempty"`
}

type FEParamGetCondicionIvaReceptor struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetCondicionIvaReceptor"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`

	ClaseCmp string `xml:"ClaseCmp,omitempty" json:"ClaseCmp,omitempty"`
}

type FEParamGetCondicionIvaReceptorResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetCondicionIvaReceptorResponse"`

	FEParamGetCondicionIvaReceptorResult *CondicionIvaReceptorResponse `xml:"FEParamGetCondicionIvaReceptorResult,omitempty" json:"FEParamGetCondicionIvaReceptorResult,omitempty"`
}

type FEParamGetTiposDoc struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposDoc"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetTiposDocResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposDocResponse"`

	FEParamGetTiposDocResult *DocTipoResponse `xml:"FEParamGetTiposDocResult,omitempty" json:"FEParamGetTiposDocResult,omitempty"`
}

type FEParamGetTiposPaises struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposPaises"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetTiposPaisesResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetTiposPaisesResponse"`

	FEParamGetTiposPaisesResult *FEPaisResponse `xml:"FEParamGetTiposPaisesResult,omitempty" json:"FEParamGetTiposPaisesResult,omitempty"`
}

type FEParamGetActividades struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetActividades"`

	Auth *FEAuthRequest `xml:"Auth,omitempty" json:"Auth,omitempty"`
}

type FEParamGetActividadesResponse struct {
	XMLName xml.Name `xml:"http://ar.gov.afip.dif.FEV1/ FEParamGetActividadesResponse"`

	FEParamGetActividadesResult *FEActividadesResponse `xml:"FEParamGetActividadesResult,omitempty" json:"FEParamGetActividadesResult,omitempty"`
}

type FEAuthRequest struct {
	Token string `xml:"Token,omitempty" json:"Token,omitempty"`

	Sign string `xml:"Sign,omitempty" json:"Sign,omitempty"`

	Cuit int64 `xml:"Cuit,omitempty" json:"Cuit,omitempty"`
}

type FECAERequest struct {
	FeCabReq *FECAECabRequest `xml:"FeCabReq,omitempty" json:"FeCabReq,omitempty"`

	FeDetReq *ArrayOfFECAEDetRequest `xml:"FeDetReq,omitempty" json:"FeDetReq,omitempty"`
}

type FECAECabRequest struct {
	*FECabRequest
}

type FECabRequest struct {
	CantReg int32 `xml:"CantReg,omitempty" json:"CantReg,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`

	CbteTipo int32 `xml:"CbteTipo,omitempty" json:"CbteTipo,omitempty"`
}

type ArrayOfFECAEDetRequest struct {
	FECAEDetRequest []*FECAEDetRequest `xml:"FECAEDetRequest,omitempty" json:"FECAEDetRequest,omitempty"`
}

type FECAEDetRequest struct {
	*FEDetRequest
}

type FEDetRequest struct {
	Concepto int32 `xml:"Concepto,omitempty" json:"Concepto,omitempty"`

	DocTipo int32 `xml:"DocTipo,omitempty" json:"DocTipo,omitempty"`

	DocNro int64 `xml:"DocNro,omitempty" json:"DocNro,omitempty"`

	CbteDesde int64 `xml:"CbteDesde,omitempty" json:"CbteDesde,omitempty"`

	CbteHasta int64 `xml:"CbteHasta,omitempty" json:"CbteHasta,omitempty"`

	CbteFch string `xml:"CbteFch,omitempty" json:"CbteFch,omitempty"`

	ImpTotal float64 `xml:"ImpTotal,omitempty" json:"ImpTotal,omitempty"`

	ImpTotConc float64 `xml:"ImpTotConc,omitempty" json:"ImpTotConc,omitempty"`

	ImpNeto float64 `xml:"ImpNeto,omitempty" json:"ImpNeto,omitempty"`

	ImpOpEx float64 `xml:"ImpOpEx,omitempty" json:"ImpOpEx,omitempty"`

	ImpTrib float64 `xml:"ImpTrib,omitempty" json:"ImpTrib,omitempty"`

	ImpIVA float64 `xml:"ImpIVA,omitempty" json:"ImpIVA,omitempty"`

	FchServDesde string `xml:"FchServDesde,omitempty" json:"FchServDesde,omitempty"`

	FchServHasta string `xml:"FchServHasta,omitempty" json:"FchServHasta,omitempty"`

	FchVtoPago string `xml:"FchVtoPago,omitempty" json:"FchVtoPago,omitempty"`

	MonId string `xml:"MonId,omitempty" json:"MonId,omitempty"`

	MonCotiz float64 `xml:"MonCotiz,omitempty" json:"MonCotiz,omitempty"`

	CanMisMonExt string `xml:"CanMisMonExt,omitempty" json:"CanMisMonExt,omitempty"`

	CondicionIVAReceptorId int32 `xml:"CondicionIVAReceptorId,omitempty" json:"CondicionIVAReceptorId,omitempty"`

	CbtesAsoc *ArrayOfCbteAsoc `xml:"CbtesAsoc,omitempty" json:"CbtesAsoc,omitempty"`

	Tributos *ArrayOfTributo `xml:"Tributos,omitempty" json:"Tributos,omitempty"`

	Iva *ArrayOfAlicIva `xml:"Iva,omitempty" json:"Iva,omitempty"`

	Opcionales *ArrayOfOpcional `xml:"Opcionales,omitempty" json:"Opcionales,omitempty"`

	Compradores *ArrayOfComprador `xml:"Compradores,omitempty" json:"Compradores,omitempty"`

	PeriodoAsoc *Periodo `xml:"PeriodoAsoc,omitempty" json:"PeriodoAsoc,omitempty"`

	Actividades *ArrayOfActividad `xml:"Actividades,omitempty" json:"Actividades,omitempty"`
}

type ArrayOfCbteAsoc struct {
	CbteAsoc []*CbteAsoc `xml:"CbteAsoc,omitempty" json:"CbteAsoc,omitempty"`
}

type CbteAsoc struct {
	Tipo int32 `xml:"Tipo,omitempty" json:"Tipo,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`

	Nro int64 `xml:"Nro,omitempty" json:"Nro,omitempty"`

	Cuit string `xml:"Cuit,omitempty" json:"Cuit,omitempty"`

	CbteFch string `xml:"CbteFch,omitempty" json:"CbteFch,omitempty"`
}

type ArrayOfTributo struct {
	Tributo []*Tributo `xml:"Tributo,omitempty" json:"Tributo,omitempty"`
}

type Tributo struct {
	Id int16 `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	BaseImp float64 `xml:"BaseImp,omitempty" json:"BaseImp,omitempty"`

	Alic float64 `xml:"Alic,omitempty" json:"Alic,omitempty"`

	Importe float64 `xml:"Importe,omitempty" json:"Importe,omitempty"`
}

type ArrayOfAlicIva struct {
	AlicIva []*AlicIva `xml:"AlicIva,omitempty" json:"AlicIva,omitempty"`
}

type AlicIva struct {
	Id int32 `xml:"Id,omitempty" json:"Id,omitempty"`

	BaseImp float64 `xml:"BaseImp,omitempty" json:"BaseImp,omitempty"`

	Importe float64 `xml:"Importe,omitempty" json:"Importe,omitempty"`
}

type ArrayOfOpcional struct {
	Opcional []*Opcional `xml:"Opcional,omitempty" json:"Opcional,omitempty"`
}

type Opcional struct {
	Id string `xml:"Id,omitempty" json:"Id,omitempty"`

	Valor string `xml:"Valor,omitempty" json:"Valor,omitempty"`
}

type ArrayOfComprador struct {
	Comprador []*Comprador `xml:"Comprador,omitempty" json:"Comprador,omitempty"`
}

type Comprador struct {
	DocTipo int32 `xml:"DocTipo,omitempty" json:"DocTipo,omitempty"`

	DocNro int64 `xml:"DocNro,omitempty" json:"DocNro,omitempty"`

	Porcentaje float64 `xml:"Porcentaje,omitempty" json:"Porcentaje,omitempty"`
}

type Periodo struct {
	FchDesde string `xml:"FchDesde,omitempty" json:"FchDesde,omitempty"`

	FchHasta string `xml:"FchHasta,omitempty" json:"FchHasta,omitempty"`
}

type ArrayOfActividad struct {
	Actividad []*Actividad `xml:"Actividad,omitempty" json:"Actividad,omitempty"`
}

type Actividad struct {
	Id int64 `xml:"Id,omitempty" json:"Id,omitempty"`
}

type FECAEResponse struct {
	FeCabResp *FECAECabResponse `xml:"FeCabResp,omitempty" json:"FeCabResp,omitempty"`

	FeDetResp *ArrayOfFECAEDetResponse `xml:"FeDetResp,omitempty" json:"FeDetResp,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`
}

type FECAECabResponse struct {
	*FECabResponse
}

type FECabResponse struct {
	Cuit int64 `xml:"Cuit,omitempty" json:"Cuit,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`

	CbteTipo int32 `xml:"CbteTipo,omitempty" json:"CbteTipo,omitempty"`

	FchProceso string `xml:"FchProceso,omitempty" json:"FchProceso,omitempty"`

	CantReg int32 `xml:"CantReg,omitempty" json:"CantReg,omitempty"`

	Resultado string `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	Reproceso string `xml:"Reproceso,omitempty" json:"Reproceso,omitempty"`
}

type ArrayOfFECAEDetResponse struct {
	FECAEDetResponse []*FECAEDetResponse `xml:"FECAEDetResponse,omitempty" json:"FECAEDetResponse,omitempty"`
}

type FECAEDetResponse struct {
	*FEDetResponse

	CAE string `xml:"CAE,omitempty" json:"CAE,omitempty"`

	CAEFchVto string `xml:"CAEFchVto,omitempty" json:"CAEFchVto,omitempty"`
}

type FEDetResponse struct {
	Concepto int32 `xml:"Concepto,omitempty" json:"Concepto,omitempty"`

	DocTipo int32 `xml:"DocTipo,omitempty" json:"DocTipo,omitempty"`

	DocNro int64 `xml:"DocNro,omitempty" json:"DocNro,omitempty"`

	CbteDesde int64 `xml:"CbteDesde,omitempty" json:"CbteDesde,omitempty"`

	CbteHasta int64 `xml:"CbteHasta,omitempty" json:"CbteHasta,omitempty"`

	CbteFch string `xml:"CbteFch,omitempty" json:"CbteFch,omitempty"`

	Resultado string `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	Observaciones *ArrayOfObs `xml:"Observaciones,omitempty" json:"Observaciones,omitempty"`
}

type ArrayOfObs struct {
	Obs []*Obs `xml:"Obs,omitempty" json:"Obs,omitempty"`
}

type Obs struct {
	Code int32 `xml:"Code,omitempty" json:"Code,omitempty"`

	Msg string `xml:"Msg,omitempty" json:"Msg,omitempty"`
}

type ArrayOfEvt struct {
	Evt []*Evt `xml:"Evt,omitempty" json:"Evt,omitempty"`
}

type Evt struct {
	Code int32 `xml:"Code,omitempty" json:"Code,omitempty"`

	Msg string `xml:"Msg,omitempty" json:"Msg,omitempty"`
}

type ArrayOfErr struct {
	Err []*Err `xml:"Err,omitempty" json:"Err,omitempty"`
}

type Err struct {
	Code int32 `xml:"Code,omitempty" json:"Code,omitempty"`

	Msg string `xml:"Msg,omitempty" json:"Msg,omitempty"`
}

type FERegXReqResponse struct {
	RegXReq int32 `xml:"RegXReq,omitempty" json:"RegXReq,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type DummyResponse struct {
	AppServer string `xml:"AppServer,omitempty" json:"AppServer,omitempty"`

	DbServer string `xml:"DbServer,omitempty" json:"DbServer,omitempty"`

	AuthServer string `xml:"AuthServer,omitempty" json:"AuthServer,omitempty"`
}

type FERecuperaLastCbteResponse struct {
	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`

	CbteTipo int32 `xml:"CbteTipo,omitempty" json:"CbteTipo,omitempty"`

	CbteNro int32 `xml:"CbteNro,omitempty" json:"CbteNro,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type FECompConsultaReq struct {
	CbteTipo int32 `xml:"CbteTipo,omitempty" json:"CbteTipo,omitempty"`

	CbteNro int64 `xml:"CbteNro,omitempty" json:"CbteNro,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`
}

type FECompConsultaResponse struct {
	ResultGet *FECompConsResponse `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type FECompConsResponse struct {
	*FECAEDetRequest

	Resultado string `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	CodAutorizacion string `xml:"CodAutorizacion,omitempty" json:"CodAutorizacion,omitempty"`

	EmisionTipo string `xml:"EmisionTipo,omitempty" json:"EmisionTipo,omitempty"`

	FchVto string `xml:"FchVto,omitempty" json:"FchVto,omitempty"`

	FchProceso string `xml:"FchProceso,omitempty" json:"FchProceso,omitempty"`

	Observaciones *ArrayOfObs `xml:"Observaciones,omitempty" json:"Observaciones,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`

	CbteTipo int32 `xml:"CbteTipo,omitempty" json:"CbteTipo,omitempty"`
}

type FECAEARequest struct {
	FeCabReq *FECAEACabRequest `xml:"FeCabReq,omitempty" json:"FeCabReq,omitempty"`

	FeDetReq *ArrayOfFECAEADetRequest `xml:"FeDetReq,omitempty" json:"FeDetReq,omitempty"`
}

type FECAEACabRequest struct {
	*FECabRequest
}

type ArrayOfFECAEADetRequest struct {
	FECAEADetRequest []*FECAEADetRequest `xml:"FECAEADetRequest,omitempty" json:"FECAEADetRequest,omitempty"`
}

type FECAEADetRequest struct {
	*FEDetRequest

	CAEA string `xml:"CAEA,omitempty" json:"CAEA,omitempty"`

	CbteFchHsGen string `xml:"CbteFchHsGen,omitempty" json:"CbteFchHsGen,omitempty"`
}

type FECAEAResponse struct {
	FeCabResp *FECAEACabResponse `xml:"FeCabResp,omitempty" json:"FeCabResp,omitempty"`

	FeDetResp *ArrayOfFECAEADetResponse `xml:"FeDetResp,omitempty" json:"FeDetResp,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`
}

type FECAEACabResponse struct {
	*FECabResponse
}

type ArrayOfFECAEADetResponse struct {
	FECAEADetResponse []*FECAEADetResponse `xml:"FECAEADetResponse,omitempty" json:"FECAEADetResponse,omitempty"`
}

type FECAEADetResponse struct {
	*FEDetResponse

	CAEA string `xml:"CAEA,omitempty" json:"CAEA,omitempty"`
}

type FECAEAGetResponse struct {
	ResultGet *FECAEAGet `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type FECAEAGet struct {
	CAEA string `xml:"CAEA,omitempty" json:"CAEA,omitempty"`

	Periodo int32 `xml:"Periodo,omitempty" json:"Periodo,omitempty"`

	Orden int16 `xml:"Orden,omitempty" json:"Orden,omitempty"`

	FchVigDesde string `xml:"FchVigDesde,omitempty" json:"FchVigDesde,omitempty"`

	FchVigHasta string `xml:"FchVigHasta,omitempty" json:"FchVigHasta,omitempty"`

	FchTopeInf string `xml:"FchTopeInf,omitempty" json:"FchTopeInf,omitempty"`

	FchProceso string `xml:"FchProceso,omitempty" json:"FchProceso,omitempty"`

	Observaciones *ArrayOfObs `xml:"Observaciones,omitempty" json:"Observaciones,omitempty"`
}

type FECAEASinMovConsResponse struct {
	ResultGet *ArrayOfFECAEASinMov `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfFECAEASinMov struct {
	FECAEASinMov []*FECAEASinMov `xml:"FECAEASinMov,omitempty" json:"FECAEASinMov,omitempty"`
}

type FECAEASinMov struct {
	CAEA string `xml:"CAEA,omitempty" json:"CAEA,omitempty"`

	FchProceso string `xml:"FchProceso,omitempty" json:"FchProceso,omitempty"`

	PtoVta int32 `xml:"PtoVta,omitempty" json:"PtoVta,omitempty"`
}

type FECAEASinMovResponse struct {
	*FECAEASinMov

	Resultado string `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type FECotizacionResponse struct {
	ResultGet *Cotizacion `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type Cotizacion struct {
	MonId string `xml:"MonId,omitempty" json:"MonId,omitempty"`

	MonCotiz float64 `xml:"MonCotiz,omitempty" json:"MonCotiz,omitempty"`

	FchCotiz string `xml:"FchCotiz,omitempty" json:"FchCotiz,omitempty"`
}

type FETributoResponse struct {
	ResultGet *ArrayOfTributoTipo `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfTributoTipo struct {
	TributoTipo []*TributoTipo `xml:"TributoTipo,omitempty" json:"TributoTipo,omitempty"`
}

type TributoTipo struct {
	Id int16 `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	FchDesde string `xml:"FchDesde,omitempty" json:"FchDesde,omitempty"`

	FchHasta string `xml:"FchHasta,omitempty" json:"FchHasta,omitempty"`
}

type MonedaResponse struct {
	ResultGet *ArrayOfMoneda `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfMoneda struct {
	Moneda []*Moneda `xml:"Moneda,omitempty" json:"Moneda,omitempty"`
}

type Moneda struct {
	Id string `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	FchDesde string `xml:"FchDesde,omitempty" json:"FchDesde,omitempty"`

	FchHasta string `xml:"FchHasta,omitempty" json:"FchHasta,omitempty"`
}

type IvaTipoResponse struct {
	ResultGet *ArrayOfIvaTipo `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfIvaTipo struct {
	IvaTipo []*IvaTipo `xml:"IvaTipo,omitempty" json:"IvaTipo,omitempty"`
}

type IvaTipo struct {
	Id string `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	FchDesde string `xml:"FchDesde,omitempty" json:"FchDesde,omitempty"`

	FchHasta string `xml:"FchHasta,omitempty" json:"FchHasta,omitempty"`
}

type OpcionalTipoResponse struct {
	ResultGet *ArrayOfOpcionalTipo `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfOpcionalTipo struct {
	OpcionalTipo []*OpcionalTipo `xml:"OpcionalTipo,omitempty" json:"OpcionalTipo,omitempty"`
}

type OpcionalTipo struct {
	Id string `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	FchDesde string `xml:"FchDesde,omitempty" json:"FchDesde,omitempty"`

	FchHasta string `xml:"FchHasta,omitempty" json:"FchHasta,omitempty"`
}

type ConceptoTipoResponse struct {
	ResultGet *ArrayOfConceptoTipo `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfConceptoTipo struct {
	ConceptoTipo []*ConceptoTipo `xml:"ConceptoTipo,omitempty" json:"ConceptoTipo,omitempty"`
}

type ConceptoTipo struct {
	Id int32 `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	FchDesde string `xml:"FchDesde,omitempty" json:"FchDesde,omitempty"`

	FchHasta string `xml:"FchHasta,omitempty" json:"FchHasta,omitempty"`
}

type FEPtoVentaResponse struct {
	ResultGet *ArrayOfPtoVenta `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfPtoVenta struct {
	PtoVenta []*PtoVenta `xml:"PtoVenta,omitempty" json:"PtoVenta,omitempty"`
}

type PtoVenta struct {
	Nro int32 `xml:"Nro,omitempty" json:"Nro,omitempty"`

	EmisionTipo string `xml:"EmisionTipo,omitempty" json:"EmisionTipo,omitempty"`

	Bloqueado string `xml:"Bloqueado,omitempty" json:"Bloqueado,omitempty"`

	FchBaja string `xml:"FchBaja,omitempty" json:"FchBaja,omitempty"`
}

type CbteTipoResponse struct {
	ResultGet *ArrayOfCbteTipo `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfCbteTipo struct {
	CbteTipo []*CbteTipo `xml:"CbteTipo,omitempty" json:"CbteTipo,omitempty"`
}

type CbteTipo struct {
	Id int32 `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	FchDesde string `xml:"FchDesde,omitempty" json:"FchDesde,omitempty"`

	FchHasta string `xml:"FchHasta,omitempty" json:"FchHasta,omitempty"`
}

type CondicionIvaReceptorResponse struct {
	ResultGet *ArrayOfCondicionIvaReceptor `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfCondicionIvaReceptor struct {
	CondicionIvaReceptor []*CondicionIvaReceptor `xml:"CondicionIvaReceptor,omitempty" json:"CondicionIvaReceptor,omitempty"`
}

type CondicionIvaReceptor struct {
	Id int32 `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	Cmp_Clase string `xml:"Cmp_Clase,omitempty" json:"Cmp_Clase,omitempty"`
}

type DocTipoResponse struct {
	ResultGet *ArrayOfDocTipo `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfDocTipo struct {
	DocTipo []*DocTipo `xml:"DocTipo,omitempty" json:"DocTipo,omitempty"`
}

type DocTipo struct {
	Id int32 `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`

	FchDesde string `xml:"FchDesde,omitempty" json:"FchDesde,omitempty"`

	FchHasta string `xml:"FchHasta,omitempty" json:"FchHasta,omitempty"`
}

type FEPaisResponse struct {
	ResultGet *ArrayOfPaisTipo `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfPaisTipo struct {
	PaisTipo []*PaisTipo `xml:"PaisTipo,omitempty" json:"PaisTipo,omitempty"`
}

type PaisTipo struct {
	Id int16 `xml:"Id,omitempty" json:"Id,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`
}

type FEActividadesResponse struct {
	ResultGet *ArrayOfActividadesTipo `xml:"ResultGet,omitempty" json:"ResultGet,omitempty"`

	Errors *ArrayOfErr `xml:"Errors,omitempty" json:"Errors,omitempty"`

	Events *ArrayOfEvt `xml:"Events,omitempty" json:"Events,omitempty"`
}

type ArrayOfActividadesTipo struct {
	ActividadesTipo []*ActividadesTipo `xml:"ActividadesTipo,omitempty" json:"ActividadesTipo,omitempty"`
}

type ActividadesTipo struct {
	Id int64 `xml:"Id,omitempty" json:"Id,omitempty"`

	Orden int16 `xml:"Orden,omitempty" json:"Orden,omitempty"`

	Desc string `xml:"Desc,omitempty" json:"Desc,omitempty"`
}

type ServiceSoap interface {

	/* Solicitud de Código de Autorización Electrónico (CAE) */
	FECAESolicitar(request *FECAESolicitar) (*FECAESolicitarResponse, error)

	FECAESolicitarContext(ctx context.Context, request *FECAESolicitar) (*FECAESolicitarResponse, error)

	/* Retorna la cantidad maxima de registros que puede tener una invocacion al metodo FECAESolicitar / FECAEARegInformativo  */
	FECompTotXRequest(request *FECompTotXRequest) (*FECompTotXRequestResponse, error)

	FECompTotXRequestContext(ctx context.Context, request *FECompTotXRequest) (*FECompTotXRequestResponse, error)

	/* Metodo dummy para verificacion de funcionamiento */
	FEDummy(request *FEDummy) (*FEDummyResponse, error)

	FEDummyContext(ctx context.Context, request *FEDummy) (*FEDummyResponse, error)

	/* Retorna el ultimo comprobante autorizado para el tipo de comprobante / cuit / punto de venta ingresado / Tipo de Emisión */
	FECompUltimoAutorizado(request *FECompUltimoAutorizado) (*FECompUltimoAutorizadoResponse, error)

	FECompUltimoAutorizadoContext(ctx context.Context, request *FECompUltimoAutorizado) (*FECompUltimoAutorizadoResponse, error)

	/* Consulta Comprobante emitido y su código. */
	FECompConsultar(request *FECompConsultar) (*FECompConsultarResponse, error)

	FECompConsultarContext(ctx context.Context, request *FECompConsultar) (*FECompConsultarResponse, error)

	/* Rendición de comprobantes asociados a un CAEA. */
	FECAEARegInformativo(request *FECAEARegInformativo) (*FECAEARegInformativoResponse, error)

	FECAEARegInformativoContext(ctx context.Context, request *FECAEARegInformativo) (*FECAEARegInformativoResponse, error)

	/* Solicitud de Código de Autorización Electrónico Anticipado (CAEA) */
	FECAEASolicitar(request *FECAEASolicitar) (*FECAEASolicitarResponse, error)

	FECAEASolicitarContext(ctx context.Context, request *FECAEASolicitar) (*FECAEASolicitarResponse, error)

	/* Consulta CAEA informado como sin movimientos. */
	FECAEASinMovimientoConsultar(request *FECAEASinMovimientoConsultar) (*FECAEASinMovimientoConsultarResponse, error)

	FECAEASinMovimientoConsultarContext(ctx context.Context, request *FECAEASinMovimientoConsultar) (*FECAEASinMovimientoConsultarResponse, error)

	/* Informa CAEA sin movimientos. */
	FECAEASinMovimientoInformar(request *FECAEASinMovimientoInformar) (*FECAEASinMovimientoInformarResponse, error)

	FECAEASinMovimientoInformarContext(ctx context.Context, request *FECAEASinMovimientoInformar) (*FECAEASinMovimientoInformarResponse, error)

	/* Consultar CAEA emitidos. */
	FECAEAConsultar(request *FECAEAConsultar) (*FECAEAConsultarResponse, error)

	FECAEAConsultarContext(ctx context.Context, request *FECAEAConsultar) (*FECAEAConsultarResponse, error)

	/* Recupera la cotizacion de la moneda consultada y su  fecha  */
	FEParamGetCotizacion(request *FEParamGetCotizacion) (*FEParamGetCotizacionResponse, error)

	FEParamGetCotizacionContext(ctx context.Context, request *FEParamGetCotizacion) (*FEParamGetCotizacionResponse, error)

	/* Recupera el listado de los diferente tributos que pueden ser utilizados  en el servicio de autorizacion */
	FEParamGetTiposTributos(request *FEParamGetTiposTributos) (*FEParamGetTiposTributosResponse, error)

	FEParamGetTiposTributosContext(ctx context.Context, request *FEParamGetTiposTributos) (*FEParamGetTiposTributosResponse, error)

	/* Recupera el listado de monedas utilizables en servicio de autorización */
	FEParamGetTiposMonedas(request *FEParamGetTiposMonedas) (*FEParamGetTiposMonedasResponse, error)

	FEParamGetTiposMonedasContext(ctx context.Context, request *FEParamGetTiposMonedas) (*FEParamGetTiposMonedasResponse, error)

	/* Recupera el listado  de Tipos de Iva utilizables en servicio de autorización. */
	FEParamGetTiposIva(request *FEParamGetTiposIva) (*FEParamGetTiposIvaResponse, error)

	FEParamGetTiposIvaContext(ctx context.Context, request *FEParamGetTiposIva) (*FEParamGetTiposIvaResponse, error)

	/* Recupera el listado de identificadores para los campos Opcionales */
	FEParamGetTiposOpcional(request *FEParamGetTiposOpcional) (*FEParamGetTiposOpcionalResponse, error)

	FEParamGetTiposOpcionalContext(ctx context.Context, request *FEParamGetTiposOpcional) (*FEParamGetTiposOpcionalResponse, error)

	/* Recupera el listado  de identificadores para el campo Concepto. */
	FEParamGetTiposConcepto(request *FEParamGetTiposConcepto) (*FEParamGetTiposConceptoResponse, error)

	FEParamGetTiposConceptoContext(ctx context.Context, request *FEParamGetTiposConcepto) (*FEParamGetTiposConceptoResponse, error)

	/* Recupera el listado de puntos de venta registrados y su estado */
	FEParamGetPtosVenta(request *FEParamGetPtosVenta) (*FEParamGetPtosVentaResponse, error)

	FEParamGetPtosVentaContext(ctx context.Context, request *FEParamGetPtosVenta) (*FEParamGetPtosVentaResponse, error)

	/* Recupera el listado  de Tipos de Comprobantes utilizables en servicio de autorización. */
	FEParamGetTiposCbte(request *FEParamGetTiposCbte) (*FEParamGetTiposCbteResponse, error)

	FEParamGetTiposCbteContext(ctx context.Context, request *FEParamGetTiposCbte) (*FEParamGetTiposCbteResponse, error)

	/* Recupera la condicion frente al IVA del receptor (para una clase de comprobante determinada o para todos si no se especifica). */
	FEParamGetCondicionIvaReceptor(request *FEParamGetCondicionIvaReceptor) (*FEParamGetCondicionIvaReceptorResponse, error)

	FEParamGetCondicionIvaReceptorContext(ctx context.Context, request *FEParamGetCondicionIvaReceptor) (*FEParamGetCondicionIvaReceptorResponse, error)

	/* Recupera el listado  de Tipos de Documentos utilizables en servicio de autorización. */
	FEParamGetTiposDoc(request *FEParamGetTiposDoc) (*FEParamGetTiposDocResponse, error)

	FEParamGetTiposDocContext(ctx context.Context, request *FEParamGetTiposDoc) (*FEParamGetTiposDocResponse, error)

	/* Recupera el listado de los diferente paises que pueden ser utilizados  en el servicio de autorizacion */
	FEParamGetTiposPaises(request *FEParamGetTiposPaises) (*FEParamGetTiposPaisesResponse, error)

	FEParamGetTiposPaisesContext(ctx context.Context, request *FEParamGetTiposPaises) (*FEParamGetTiposPaisesResponse, error)

	/* Recupera el listado de las diferentes actividades habilitadas para el emisor */
	FEParamGetActividades(request *FEParamGetActividades) (*FEParamGetActividadesResponse, error)

	FEParamGetActividadesContext(ctx context.Context, request *FEParamGetActividades) (*FEParamGetActividadesResponse, error)
}

type serviceSoap struct {
	client *soap.Client
}

func NewServiceSoap(client *soap.Client) ServiceSoap {
	return &serviceSoap{
		client: client,
	}
}

func (service *serviceSoap) FECAESolicitarContext(ctx context.Context, request *FECAESolicitar) (*FECAESolicitarResponse, error) {
	response := new(FECAESolicitarResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECAESolicitar", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECAESolicitar(request *FECAESolicitar) (*FECAESolicitarResponse, error) {
	return service.FECAESolicitarContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FECompTotXRequestContext(ctx context.Context, request *FECompTotXRequest) (*FECompTotXRequestResponse, error) {
	response := new(FECompTotXRequestResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECompTotXRequest", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECompTotXRequest(request *FECompTotXRequest) (*FECompTotXRequestResponse, error) {
	return service.FECompTotXRequestContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEDummyContext(ctx context.Context, request *FEDummy) (*FEDummyResponse, error) {
	response := new(FEDummyResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEDummy", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEDummy(request *FEDummy) (*FEDummyResponse, error) {
	return service.FEDummyContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FECompUltimoAutorizadoContext(ctx context.Context, request *FECompUltimoAutorizado) (*FECompUltimoAutorizadoResponse, error) {
	response := new(FECompUltimoAutorizadoResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECompUltimoAutorizado(request *FECompUltimoAutorizado) (*FECompUltimoAutorizadoResponse, error) {
	return service.FECompUltimoAutorizadoContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FECompConsultarContext(ctx context.Context, request *FECompConsultar) (*FECompConsultarResponse, error) {
	response := new(FECompConsultarResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECompConsultar", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECompConsultar(request *FECompConsultar) (*FECompConsultarResponse, error) {
	return service.FECompConsultarContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FECAEARegInformativoContext(ctx context.Context, request *FECAEARegInformativo) (*FECAEARegInformativoResponse, error) {
	response := new(FECAEARegInformativoResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECAEARegInformativo", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECAEARegInformativo(request *FECAEARegInformativo) (*FECAEARegInformativoResponse, error) {
	return service.FECAEARegInformativoContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FECAEASolicitarContext(ctx context.Context, request *FECAEASolicitar) (*FECAEASolicitarResponse, error) {
	response := new(FECAEASolicitarResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECAEASolicitar", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECAEASolicitar(request *FECAEASolicitar) (*FECAEASolicitarResponse, error) {
	return service.FECAEASolicitarContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FECAEASinMovimientoConsultarContext(ctx context.Context, request *FECAEASinMovimientoConsultar) (*FECAEASinMovimientoConsultarResponse, error) {
	response := new(FECAEASinMovimientoConsultarResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECAEASinMovimientoConsultar(request *FECAEASinMovimientoConsultar) (*FECAEASinMovimientoConsultarResponse, error) {
	return service.FECAEASinMovimientoConsultarContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FECAEASinMovimientoInformarContext(ctx context.Context, request *FECAEASinMovimientoInformar) (*FECAEASinMovimientoInformarResponse, error) {
	response := new(FECAEASinMovimientoInformarResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECAEASinMovimientoInformar(request *FECAEASinMovimientoInformar) (*FECAEASinMovimientoInformarResponse, error) {
	return service.FECAEASinMovimientoInformarContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FECAEAConsultarContext(ctx context.Context, request *FECAEAConsultar) (*FECAEAConsultarResponse, error) {
	response := new(FECAEAConsultarResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FECAEAConsultar", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FECAEAConsultar(request *FECAEAConsultar) (*FECAEAConsultarResponse, error) {
	return service.FECAEAConsultarContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetCotizacionContext(ctx context.Context, request *FEParamGetCotizacion) (*FEParamGetCotizacionResponse, error) {
	response := new(FEParamGetCotizacionResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetCotizacion(request *FEParamGetCotizacion) (*FEParamGetCotizacionResponse, error) {
	return service.FEParamGetCotizacionContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetTiposTributosContext(ctx context.Context, request *FEParamGetTiposTributos) (*FEParamGetTiposTributosResponse, error) {
	response := new(FEParamGetTiposTributosResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetTiposTributos(request *FEParamGetTiposTributos) (*FEParamGetTiposTributosResponse, error) {
	return service.FEParamGetTiposTributosContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetTiposMonedasContext(ctx context.Context, request *FEParamGetTiposMonedas) (*FEParamGetTiposMonedasResponse, error) {
	response := new(FEParamGetTiposMonedasResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetTiposMonedas(request *FEParamGetTiposMonedas) (*FEParamGetTiposMonedasResponse, error) {
	return service.FEParamGetTiposMonedasContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetTiposIvaContext(ctx context.Context, request *FEParamGetTiposIva) (*FEParamGetTiposIvaResponse, error) {
	response := new(FEParamGetTiposIvaResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetTiposIva(request *FEParamGetTiposIva) (*FEParamGetTiposIvaResponse, error) {
	return service.FEParamGetTiposIvaContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetTiposOpcionalContext(ctx context.Context, request *FEParamGetTiposOpcional) (*FEParamGetTiposOpcionalResponse, error) {
	response := new(FEParamGetTiposOpcionalResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetTiposOpcional(request *FEParamGetTiposOpcional) (*FEParamGetTiposOpcionalResponse, error) {
	return service.FEParamGetTiposOpcionalContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetTiposConceptoContext(ctx context.Context, request *FEParamGetTiposConcepto) (*FEParamGetTiposConceptoResponse, error) {
	response := new(FEParamGetTiposConceptoResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetTiposConcepto(request *FEParamGetTiposConcepto) (*FEParamGetTiposConceptoResponse, error) {
	return service.FEParamGetTiposConceptoContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetPtosVentaContext(ctx context.Context, request *FEParamGetPtosVenta) (*FEParamGetPtosVentaResponse, error) {
	response := new(FEParamGetPtosVentaResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetPtosVenta(request *FEParamGetPtosVenta) (*FEParamGetPtosVentaResponse, error) {
	return service.FEParamGetPtosVentaContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetTiposCbteContext(ctx context.Context, request *FEParamGetTiposCbte) (*FEParamGetTiposCbteResponse, error) {
	response := new(FEParamGetTiposCbteResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetTiposCbte(request *FEParamGetTiposCbte) (*FEParamGetTiposCbteResponse, error) {
	return service.FEParamGetTiposCbteContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetCondicionIvaReceptorContext(ctx context.Context, request *FEParamGetCondicionIvaReceptor) (*FEParamGetCondicionIvaReceptorResponse, error) {
	response := new(FEParamGetCondicionIvaReceptorResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetCondicionIvaReceptor", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetCondicionIvaReceptor(request *FEParamGetCondicionIvaReceptor) (*FEParamGetCondicionIvaReceptorResponse, error) {
	return service.FEParamGetCondicionIvaReceptorContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetTiposDocContext(ctx context.Context, request *FEParamGetTiposDoc) (*FEParamGetTiposDocResponse, error) {
	response := new(FEParamGetTiposDocResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetTiposDoc(request *FEParamGetTiposDoc) (*FEParamGetTiposDocResponse, error) {
	return service.FEParamGetTiposDocContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetTiposPaisesContext(ctx context.Context, request *FEParamGetTiposPaises) (*FEParamGetTiposPaisesResponse, error) {
	response := new(FEParamGetTiposPaisesResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetTiposPaises(request *FEParamGetTiposPaises) (*FEParamGetTiposPaisesResponse, error) {
	return service.FEParamGetTiposPaisesContext(
		context.Background(),
		request,
	)
}

func (service *serviceSoap) FEParamGetActividadesContext(ctx context.Context, request *FEParamGetActividades) (*FEParamGetActividadesResponse, error) {
	response := new(FEParamGetActividadesResponse)
	err := service.client.CallContext(ctx, "http://ar.gov.afip.dif.FEV1/FEParamGetActividades", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *serviceSoap) FEParamGetActividades(request *FEParamGetActividades) (*FEParamGetActividadesResponse, error) {
	return service.FEParamGetActividadesContext(
		context.Background(),
		request,
	)
}
