// Code generated by gowsdl DO NOT EDIT.

package wscoemcons

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type ObtenerConsultaEstadosCOEM struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque ObtenerConsultaEstadosCOEM"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	IdentificadorCabecera string `xml:"identificadorCabecera,omitempty" json:"identificadorCabecera,omitempty"`
}

type ObtenerConsultaEstadosCOEMResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque ObtenerConsultaEstadosCOEMResponse"`

	ObtenerConsultaEstadosCOEMResult *ResultadoEjecucionOfResultadoEstadoProceso `xml:"ObtenerConsultaEstadosCOEMResult,omitempty" json:"ObtenerConsultaEstadosCOEMResult,omitempty"`
}

type ObtenerConsultaNoAbordo struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque ObtenerConsultaNoAbordo"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	IdentificadorCabecera string `xml:"identificadorCabecera,omitempty" json:"identificadorCabecera,omitempty"`
}

type ObtenerConsultaNoAbordoResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque ObtenerConsultaNoAbordoResponse"`

	ObtenerConsultaNoAbordoResult *ResultadoEjecucionOfResultadoNoAbordoProceso `xml:"ObtenerConsultaNoAbordoResult,omitempty" json:"ObtenerConsultaNoAbordoResult,omitempty"`
}

type ObtenerConsultaSolicitudes struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque ObtenerConsultaSolicitudes"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	IdentificadorCabecera string `xml:"identificadorCabecera,omitempty" json:"identificadorCabecera,omitempty"`
}

type ObtenerConsultaSolicitudesResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque ObtenerConsultaSolicitudesResponse"`

	ObtenerConsultaSolicitudesResult *ResultadoEjecucionOfResultadoSolicitudProceso `xml:"ObtenerConsultaSolicitudesResult,omitempty" json:"ObtenerConsultaSolicitudesResult,omitempty"`
}

type DummyTestConnection struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque DummyTestConnection"`

	WsAutenticacion *WSAutenticacionEmpresa `xml:"wsAutenticacion,omitempty" json:"wsAutenticacion,omitempty"`

	DummyTestConnectionInput *DummyTestConnectionInput `xml:"dummyTestConnectionInput,omitempty" json:"dummyTestConnectionInput,omitempty"`
}

type DummyTestConnectionResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque DummyTestConnectionResponse"`

	DummyTestConnectionResult *ResultadoEjecucionOfDummyTestConnectionOutput `xml:"DummyTestConnectionResult,omitempty" json:"DummyTestConnectionResult,omitempty"`
}

type DummyTestConnectionOrg struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque DummyTestConnectionOrg"`

	WsAutenticacion *WSAutenticacionOrganismo `xml:"wsAutenticacion,omitempty" json:"wsAutenticacion,omitempty"`

	DummyTestConnectionInput *DummyTestConnectionInput `xml:"dummyTestConnectionInput,omitempty" json:"dummyTestConnectionInput,omitempty"`
}

type DummyTestConnectionOrgResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque DummyTestConnectionOrgResponse"`

	DummyTestConnectionOrgResult *ResultadoEjecucionOfDummyTestConnectionOutput `xml:"DummyTestConnectionOrgResult,omitempty" json:"DummyTestConnectionOrgResult,omitempty"`
}

type Dummy struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque Dummy"`
}

type DummyResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wconscomunicacionembarque DummyResponse"`

	DummyResult *ResultadoEjecucionOfDummyOutput `xml:"DummyResult,omitempty" json:"DummyResult,omitempty"`
}

type WSAutenticacionEmpresa struct {
	*WSAutenticacion

	CuitEmpresaConectada int64 `xml:"CuitEmpresaConectada,omitempty" json:"CuitEmpresaConectada,omitempty"`

	TipoAgente string `xml:"TipoAgente,omitempty" json:"TipoAgente,omitempty"`

	Rol string `xml:"Rol,omitempty" json:"Rol,omitempty"`
}

type WSAutenticacion struct {
	Token string `xml:"Token,omitempty" json:"Token,omitempty"`

	Sign string `xml:"Sign,omitempty" json:"Sign,omitempty"`
}

type ResultadoEjecucionOfResultadoEstadoProceso struct {
	Server string `xml:"Server,omitempty" json:"Server,omitempty"`

	TimeStamp soap.XSDDateTime `xml:"TimeStamp,omitempty" json:"TimeStamp,omitempty"`

	Resultado *ResultadoEstadoProceso `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	Errores *ArrayOfErrorEjecucion `xml:"Errores,omitempty" json:"Errores,omitempty"`
}

type ResultadoEstadoProceso struct {
	*AbstractEntidadOfString

	Listado *ArrayOfConsultaEstadoCOEM `xml:"Listado,omitempty" json:"Listado,omitempty"`

	InformacionAdicional string `xml:"InformacionAdicional,omitempty" json:"InformacionAdicional,omitempty"`
}

type AbstractEntidadOfString struct {
	*AbstractEntidadGenerica
}

type AbstractEntidadGenerica struct {
}

type ConsultaEstadoCOEM struct {
	*AbstractEntidadOfString

	IdentificadorCOEM string `xml:"IdentificadorCOEM,omitempty" json:"IdentificadorCOEM,omitempty"`

	CuitAlta string `xml:"CuitAlta,omitempty" json:"CuitAlta,omitempty"`

	Motivo string `xml:"Motivo,omitempty" json:"Motivo,omitempty"`

	FechaEstado *soap.XSDDateTime `xml:"FechaEstado,omitempty" json:"FechaEstado,omitempty"`

	Estado string `xml:"Estado,omitempty" json:"Estado,omitempty"`

	CODE string `xml:"CODE,omitempty" json:"CODE,omitempty"`
}

type ArrayOfConsultaEstadoCOEM struct {
	ConsultaEstadoCOEM []*ConsultaEstadoCOEM `xml:"ConsultaEstadoCOEM,omitempty" json:"ConsultaEstadoCOEM,omitempty"`
}

type ArrayOfErrorEjecucion struct {
	ErrorEjecucion []*ErrorEjecucion `xml:"ErrorEjecucion,omitempty" json:"ErrorEjecucion,omitempty"`
}

type ErrorEjecucion struct {
	Codigo string `xml:"Codigo,omitempty" json:"Codigo,omitempty"`

	Descripcion string `xml:"Descripcion,omitempty" json:"Descripcion,omitempty"`
}

type ResultadoEjecucionOfResultadoNoAbordoProceso struct {
	Server string `xml:"Server,omitempty" json:"Server,omitempty"`

	TimeStamp soap.XSDDateTime `xml:"TimeStamp,omitempty" json:"TimeStamp,omitempty"`

	Resultado *ResultadoNoAbordoProceso `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	Errores *ArrayOfErrorEjecucion `xml:"Errores,omitempty" json:"Errores,omitempty"`
}

type ResultadoNoAbordoProceso struct {
	*AbstractEntidadOfString

	Listado *ArrayOfConsultaNoAbordo `xml:"Listado,omitempty" json:"Listado,omitempty"`

	InformacionAdicional string `xml:"InformacionAdicional,omitempty" json:"InformacionAdicional,omitempty"`
}

type ArrayOfConsultaNoAbordo struct {
	ConsultaNoAbordo []*ConsultaNoAbordo `xml:"ConsultaNoAbordo,omitempty" json:"ConsultaNoAbordo,omitempty"`
}

type ConsultaNoAbordo struct {
	*AbstractEntidadOfString

	IdentificadorCACE string `xml:"IdentificadorCACE,omitempty" json:"IdentificadorCACE,omitempty"`

	IdentificadorCOEM string `xml:"IdentificadorCOEM,omitempty" json:"IdentificadorCOEM,omitempty"`

	Tipo string `xml:"Tipo,omitempty" json:"Tipo,omitempty"`

	Contenedor string `xml:"Contenedor,omitempty" json:"Contenedor,omitempty"`

	Destinacion string `xml:"Destinacion,omitempty" json:"Destinacion,omitempty"`

	Cuit string `xml:"Cuit,omitempty" json:"Cuit,omitempty"`

	FechaNoAbordo *soap.XSDDateTime `xml:"FechaNoAbordo,omitempty" json:"FechaNoAbordo,omitempty"`

	TipoNoAbordo string `xml:"TipoNoAbordo,omitempty" json:"TipoNoAbordo,omitempty"`

	MotivoNoAbordo string `xml:"MotivoNoAbordo,omitempty" json:"MotivoNoAbordo,omitempty"`

	DescripcionMotivo string `xml:"DescripcionMotivo,omitempty" json:"DescripcionMotivo,omitempty"`
}

type ResultadoEjecucionOfResultadoSolicitudProceso struct {
	Server string `xml:"Server,omitempty" json:"Server,omitempty"`

	TimeStamp soap.XSDDateTime `xml:"TimeStamp,omitempty" json:"TimeStamp,omitempty"`

	Resultado *ResultadoSolicitudProceso `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	Errores *ArrayOfErrorEjecucion `xml:"Errores,omitempty" json:"Errores,omitempty"`
}

type ResultadoSolicitudProceso struct {
	*AbstractEntidadOfString

	Listado *ArrayOfConsultaSolicitudes `xml:"Listado,omitempty" json:"Listado,omitempty"`

	InformacionAdicional string `xml:"InformacionAdicional,omitempty" json:"InformacionAdicional,omitempty"`
}

type ArrayOfConsultaSolicitudes struct {
	ConsultaSolicitudes []*ConsultaSolicitudes `xml:"ConsultaSolicitudes,omitempty" json:"ConsultaSolicitudes,omitempty"`
}

type ConsultaSolicitudes struct {
	*AbstractEntidadOfString

	IdentificadorCACE string `xml:"IdentificadorCACE,omitempty" json:"IdentificadorCACE,omitempty"`

	NumeroSolicitud string `xml:"NumeroSolicitud,omitempty" json:"NumeroSolicitud,omitempty"`

	IdentificadorCOEM string `xml:"IdentificadorCOEM,omitempty" json:"IdentificadorCOEM,omitempty"`

	Estado string `xml:"Estado,omitempty" json:"Estado,omitempty"`

	FechaEstado *soap.XSDDateTime `xml:"FechaEstado,omitempty" json:"FechaEstado,omitempty"`

	TipoSolicitud string `xml:"TipoSolicitud,omitempty" json:"TipoSolicitud,omitempty"`
}

type DummyTestConnectionInput struct {
	SimularRespuestaConErrores bool `xml:"SimularRespuestaConErrores,omitempty" json:"SimularRespuestaConErrores,omitempty"`
}

type ResultadoEjecucionOfDummyTestConnectionOutput struct {
	Server string `xml:"Server,omitempty" json:"Server,omitempty"`

	TimeStamp soap.XSDDateTime `xml:"TimeStamp,omitempty" json:"TimeStamp,omitempty"`

	Resultado *DummyTestConnectionOutput `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	Errores *ArrayOfErrorEjecucion `xml:"Errores,omitempty" json:"Errores,omitempty"`
}

type DummyTestConnectionOutput struct {
	*AbstractEntidadOfInt32

	NumericoEntero int32 `xml:"NumericoEntero,omitempty" json:"NumericoEntero,omitempty"`

	NumericoDecimal float64 `xml:"NumericoDecimal,omitempty" json:"NumericoDecimal,omitempty"`

	Caracteres string `xml:"Caracteres,omitempty" json:"Caracteres,omitempty"`

	Fecha soap.XSDDateTime `xml:"Fecha,omitempty" json:"Fecha,omitempty"`
}

type AbstractEntidadOfInt32 struct {
	*AbstractEntidadGenerica
}

type WSAutenticacionOrganismo struct {
	*WSAutenticacion

	CuitOrganismo int64 `xml:"CuitOrganismo,omitempty" json:"CuitOrganismo,omitempty"`

	CuitUsuarioConectado int64 `xml:"CuitUsuarioConectado,omitempty" json:"CuitUsuarioConectado,omitempty"`

	CuitEmpresaConectada int64 `xml:"CuitEmpresaConectada,omitempty" json:"CuitEmpresaConectada,omitempty"`

	TipoAgente string `xml:"TipoAgente,omitempty" json:"TipoAgente,omitempty"`

	Rol string `xml:"Rol,omitempty" json:"Rol,omitempty"`
}

type ResultadoEjecucionOfDummyOutput struct {
	Server string `xml:"Server,omitempty" json:"Server,omitempty"`

	TimeStamp soap.XSDDateTime `xml:"TimeStamp,omitempty" json:"TimeStamp,omitempty"`

	Resultado *DummyOutput `xml:"Resultado,omitempty" json:"Resultado,omitempty"`

	Errores *ArrayOfErrorEjecucion `xml:"Errores,omitempty" json:"Errores,omitempty"`
}

type DummyOutput struct {
	AppServer string `xml:"AppServer,omitempty" json:"AppServer,omitempty"`

	DbServer string `xml:"DbServer,omitempty" json:"DbServer,omitempty"`

	AuthServer string `xml:"AuthServer,omitempty" json:"AuthServer,omitempty"`
}

type WconscomunicacionembarqueSoap interface {

	/* Obtiene el listado de coems con sus estados */
	ObtenerConsultaEstadosCOEM(request *ObtenerConsultaEstadosCOEM) (*ObtenerConsultaEstadosCOEMResponse, error)

	ObtenerConsultaEstadosCOEMContext(ctx context.Context, request *ObtenerConsultaEstadosCOEM) (*ObtenerConsultaEstadosCOEMResponse, error)

	/* Obtiene el listado de COEMS No Abordo */
	ObtenerConsultaNoAbordo(request *ObtenerConsultaNoAbordo) (*ObtenerConsultaNoAbordoResponse, error)

	ObtenerConsultaNoAbordoContext(ctx context.Context, request *ObtenerConsultaNoAbordo) (*ObtenerConsultaNoAbordoResponse, error)

	/* Obtiene el listado de coems con sus estados */
	ObtenerConsultaSolicitudes(request *ObtenerConsultaSolicitudes) (*ObtenerConsultaSolicitudesResponse, error)

	ObtenerConsultaSolicitudesContext(ctx context.Context, request *ObtenerConsultaSolicitudes) (*ObtenerConsultaSolicitudesResponse, error)

	/* Web Method de testeo de los parametros de conexion para Empresas con salida ok o con errores segun bool en parametro de entrada. */
	DummyTestConnection(request *DummyTestConnection) (*DummyTestConnectionResponse, error)

	DummyTestConnectionContext(ctx context.Context, request *DummyTestConnection) (*DummyTestConnectionResponse, error)

	/* Web Method de testeo de los parametros de conexion para Organismos con salida ok o con errores segun bool en parametro de entrada. */
	DummyTestConnectionOrg(request *DummyTestConnectionOrg) (*DummyTestConnectionOrgResponse, error)

	DummyTestConnectionOrgContext(ctx context.Context, request *DummyTestConnectionOrg) (*DummyTestConnectionOrgResponse, error)

	/* Web Method para testeo del correcto funcionamiento del Web Service. */
	Dummy(request *Dummy) (*DummyResponse, error)

	DummyContext(ctx context.Context, request *Dummy) (*DummyResponse, error)
}

type wconscomunicacionembarqueSoap struct {
	client *soap.Client
}

func NewWconscomunicacionembarqueSoap(client *soap.Client) WconscomunicacionembarqueSoap {
	return &wconscomunicacionembarqueSoap{
		client: client,
	}
}

func (service *wconscomunicacionembarqueSoap) ObtenerConsultaEstadosCOEMContext(ctx context.Context, request *ObtenerConsultaEstadosCOEM) (*ObtenerConsultaEstadosCOEMResponse, error) {
	response := new(ObtenerConsultaEstadosCOEMResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaEstadosCOEM", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wconscomunicacionembarqueSoap) ObtenerConsultaEstadosCOEM(request *ObtenerConsultaEstadosCOEM) (*ObtenerConsultaEstadosCOEMResponse, error) {
	return service.ObtenerConsultaEstadosCOEMContext(
		context.Background(),
		request,
	)
}

func (service *wconscomunicacionembarqueSoap) ObtenerConsultaNoAbordoContext(ctx context.Context, request *ObtenerConsultaNoAbordo) (*ObtenerConsultaNoAbordoResponse, error) {
	response := new(ObtenerConsultaNoAbordoResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaNoAbordo", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wconscomunicacionembarqueSoap) ObtenerConsultaNoAbordo(request *ObtenerConsultaNoAbordo) (*ObtenerConsultaNoAbordoResponse, error) {
	return service.ObtenerConsultaNoAbordoContext(
		context.Background(),
		request,
	)
}

func (service *wconscomunicacionembarqueSoap) ObtenerConsultaSolicitudesContext(ctx context.Context, request *ObtenerConsultaSolicitudes) (*ObtenerConsultaSolicitudesResponse, error) {
	response := new(ObtenerConsultaSolicitudesResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wconscomunicacionembarque/ObtenerConsultaSolicitudes", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wconscomunicacionembarqueSoap) ObtenerConsultaSolicitudes(request *ObtenerConsultaSolicitudes) (*ObtenerConsultaSolicitudesResponse, error) {
	return service.ObtenerConsultaSolicitudesContext(
		context.Background(),
		request,
	)
}

func (service *wconscomunicacionembarqueSoap) DummyTestConnectionContext(ctx context.Context, request *DummyTestConnection) (*DummyTestConnectionResponse, error) {
	response := new(DummyTestConnectionResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wconscomunicacionembarque/DummyTestConnection", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wconscomunicacionembarqueSoap) DummyTestConnection(request *DummyTestConnection) (*DummyTestConnectionResponse, error) {
	return service.DummyTestConnectionContext(
		context.Background(),
		request,
	)
}

func (service *wconscomunicacionembarqueSoap) DummyTestConnectionOrgContext(ctx context.Context, request *DummyTestConnectionOrg) (*DummyTestConnectionOrgResponse, error) {
	response := new(DummyTestConnectionOrgResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wconscomunicacionembarque/DummyTestConnectionOrg", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wconscomunicacionembarqueSoap) DummyTestConnectionOrg(request *DummyTestConnectionOrg) (*DummyTestConnectionOrgResponse, error) {
	return service.DummyTestConnectionOrgContext(
		context.Background(),
		request,
	)
}

func (service *wconscomunicacionembarqueSoap) DummyContext(ctx context.Context, request *Dummy) (*DummyResponse, error) {
	response := new(DummyResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wconscomunicacionembarque/Dummy", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wconscomunicacionembarqueSoap) Dummy(request *Dummy) (*DummyResponse, error) {
	return service.DummyContext(
		context.Background(),
		request,
	)
}
