// Code generated by gowsdl DO NOT EDIT.

package wscoem

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type RegistrarCaratula struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque RegistrarCaratula"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgRegistrarCaratula *RegistrarCaratulaRequest `xml:"argRegistrarCaratula,omitempty" json:"argRegistrarCaratula,omitempty"`
}

type RegistrarCaratulaResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque RegistrarCaratulaResponse"`

	RegistrarCaratulaResult *RegistrarEmbarqueRta `xml:"RegistrarCaratulaResult,omitempty" json:"RegistrarCaratulaResult,omitempty"`
}

type RectificarCaratula struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque RectificarCaratula"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgRectificarCaratula *RectificarCaratulaRequest `xml:"argRectificarCaratula,omitempty" json:"argRectificarCaratula,omitempty"`
}

type RectificarCaratulaResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque RectificarCaratulaResponse"`

	RectificarCaratulaResult *RectificarEmbarqueRta `xml:"RectificarCaratulaResult,omitempty" json:"RectificarCaratulaResult,omitempty"`
}

type AnularCaratula struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque AnularCaratula"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgAnularCaratula *AnularCaratulaRequest `xml:"argAnularCaratula,omitempty" json:"argAnularCaratula,omitempty"`
}

type AnularCaratulaResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque AnularCaratulaResponse"`

	AnularCaratulaResult *AnularEmbarqueRta `xml:"AnularCaratulaResult,omitempty" json:"AnularCaratulaResult,omitempty"`
}

type RegistrarCOEM struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque RegistrarCOEM"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgRegistrarCOEM *RegistrarCOEMRequest `xml:"argRegistrarCOEM,omitempty" json:"argRegistrarCOEM,omitempty"`
}

type RegistrarCOEMResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque RegistrarCOEMResponse"`

	RegistrarCOEMResult *RegistrarEmbarqueRta `xml:"RegistrarCOEMResult,omitempty" json:"RegistrarCOEMResult,omitempty"`
}

type RectificarCOEM struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque RectificarCOEM"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgRectificarCOEM *RectificarCOEMRequest `xml:"argRectificarCOEM,omitempty" json:"argRectificarCOEM,omitempty"`
}

type RectificarCOEMResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque RectificarCOEMResponse"`

	RectificarCOEMResult *RectificarEmbarqueRta `xml:"RectificarCOEMResult,omitempty" json:"RectificarCOEMResult,omitempty"`
}

type AnularCOEM struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque AnularCOEM"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgAnularCOEM *AnularCOEMRequest `xml:"argAnularCOEM,omitempty" json:"argAnularCOEM,omitempty"`
}

type AnularCOEMResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque AnularCOEMResponse"`

	AnularCOEMResult *AnularEmbarqueRta `xml:"AnularCOEMResult,omitempty" json:"AnularCOEMResult,omitempty"`
}

type CerrarCOEM struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque CerrarCOEM"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgCerrarCOEM *CerrarCOEMRequest `xml:"argCerrarCOEM,omitempty" json:"argCerrarCOEM,omitempty"`
}

type CerrarCOEMResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque CerrarCOEMResponse"`

	CerrarCOEMResult *RegistrarEmbarqueRta `xml:"CerrarCOEMResult,omitempty" json:"CerrarCOEMResult,omitempty"`
}

type SolicitarCambioBuque struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCambioBuque"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgSolicitarCambioBuque *SolicitarCambioBuqueRequest `xml:"argSolicitarCambioBuque,omitempty" json:"argSolicitarCambioBuque,omitempty"`
}

type SolicitarCambioBuqueResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCambioBuqueResponse"`

	SolicitarCambioBuqueResult *RegistrarEmbarqueRta `xml:"SolicitarCambioBuqueResult,omitempty" json:"SolicitarCambioBuqueResult,omitempty"`
}

type SolicitarCambioFechas struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCambioFechas"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgSolicitarCambioFechas *SolicitarCambioFechasRequest `xml:"argSolicitarCambioFechas,omitempty" json:"argSolicitarCambioFechas,omitempty"`
}

type SolicitarCambioFechasResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCambioFechasResponse"`

	SolicitarCambioFechasResult *RegistrarEmbarqueRta `xml:"SolicitarCambioFechasResult,omitempty" json:"SolicitarCambioFechasResult,omitempty"`
}

type SolicitarCambioLOT struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCambioLOT"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgSolicitarCambioLOT *SolicitarCambioLOTRequest `xml:"argSolicitarCambioLOT,omitempty" json:"argSolicitarCambioLOT,omitempty"`
}

type SolicitarCambioLOTResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCambioLOTResponse"`

	SolicitarCambioLOTResult *RegistrarEmbarqueRta `xml:"SolicitarCambioLOTResult,omitempty" json:"SolicitarCambioLOTResult,omitempty"`
}

type SolicitarNoABordo struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarNoABordo"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgSolicitarNoABordo *SolicitarNoABordoRequest `xml:"argSolicitarNoABordo,omitempty" json:"argSolicitarNoABordo,omitempty"`
}

type SolicitarNoABordoResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarNoABordoResponse"`

	SolicitarNoABordoResult *RegistrarEmbarqueRta `xml:"SolicitarNoABordoResult,omitempty" json:"SolicitarNoABordoResult,omitempty"`
}

type SolicitarCierreCargaContoBulto struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCierreCargaContoBulto"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgSolicitarCierreCargaContoBulto *SolicitarCierreCargaContoBultoRequest `xml:"argSolicitarCierreCargaContoBulto,omitempty" json:"argSolicitarCierreCargaContoBulto,omitempty"`
}

type SolicitarCierreCargaContoBultoResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCierreCargaContoBultoResponse"`

	SolicitarCierreCargaContoBultoResult *RegistrarEmbarqueRta `xml:"SolicitarCierreCargaContoBultoResult,omitempty" json:"SolicitarCierreCargaContoBultoResult,omitempty"`
}

type SolicitarCierreCargaGranel struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCierreCargaGranel"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgSolicitarCierreCargaGranel *SolicitarCierreCargaGranelRequest `xml:"argSolicitarCierreCargaGranel,omitempty" json:"argSolicitarCierreCargaGranel,omitempty"`
}

type SolicitarCierreCargaGranelResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarCierreCargaGranelResponse"`

	SolicitarCierreCargaGranelResult *RegistrarEmbarqueRta `xml:"SolicitarCierreCargaGranelResult,omitempty" json:"SolicitarCierreCargaGranelResult,omitempty"`
}

type SolicitarAnulacionCOEM struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarAnulacionCOEM"`

	ArgWSAutenticacionEmpresa *WSAutenticacionEmpresa `xml:"argWSAutenticacionEmpresa,omitempty" json:"argWSAutenticacionEmpresa,omitempty"`

	ArgSolicitarAnulacionCOEM *SolicitarAnulacionCOEMRequest `xml:"argSolicitarAnulacionCOEM,omitempty" json:"argSolicitarAnulacionCOEM,omitempty"`
}

type SolicitarAnulacionCOEMResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque SolicitarAnulacionCOEMResponse"`

	SolicitarAnulacionCOEMResult *RegistrarEmbarqueRta `xml:"SolicitarAnulacionCOEMResult,omitempty" json:"SolicitarAnulacionCOEMResult,omitempty"`
}

type Dummy struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque Dummy"`
}

type DummyResponse struct {
	XMLName xml.Name `xml:"Ar.Gob.Afip.Dga.wgescomunicacionembarque DummyResponse"`

	DummyResult *ResultadoEjecucionDummy `xml:"DummyResult,omitempty" json:"DummyResult,omitempty"`
}

type WSAutenticacionEmpresa struct {
	*WSAutenticacion

	CuitEmpresaConectada int64 `xml:"CuitEmpresaConectada,omitempty" json:"CuitEmpresaConectada,omitempty"`

	TipoAgente string `xml:"TipoAgente,omitempty" json:"TipoAgente,omitempty"`

	Rol string `xml:"Rol,omitempty" json:"Rol,omitempty"`
}

type WSAutenticacion struct {
	Token string `xml:"Token,omitempty" json:"Token,omitempty"`

	Sign string `xml:"Sign,omitempty" json:"Sign,omitempty"`
}

type RegistrarCaratulaRequest struct {
	Caratula *Caratula `xml:"Caratula,omitempty" json:"Caratula,omitempty"`
}

type Caratula struct {
	IdentificadorBuque string `xml:"IdentificadorBuque,omitempty" json:"IdentificadorBuque,omitempty"`

	CodigoAduana string `xml:"CodigoAduana,omitempty" json:"CodigoAduana,omitempty"`

	CodigoLugarOperativo string `xml:"CodigoLugarOperativo,omitempty" json:"CodigoLugarOperativo,omitempty"`

	FechaArribo soap.XSDDateTime `xml:"FechaArribo,omitempty" json:"FechaArribo,omitempty"`

	FechaZarpada soap.XSDDateTime `xml:"FechaZarpada,omitempty" json:"FechaZarpada,omitempty"`

	Via string `xml:"Via,omitempty" json:"Via,omitempty"`

	NombreMedioTransporte string `xml:"NombreMedioTransporte,omitempty" json:"NombreMedioTransporte,omitempty"`

	PuertoDestino string `xml:"PuertoDestino,omitempty" json:"PuertoDestino,omitempty"`

	NumeroViaje string `xml:"NumeroViaje,omitempty" json:"NumeroViaje,omitempty"`

	Itinerario *ArrayOfPuerto `xml:"Itinerario,omitempty" json:"Itinerario,omitempty"`
}

type ArrayOfPuerto struct {
	Puerto []*Puerto `xml:"Puerto,omitempty" json:"Puerto,omitempty"`
}

type Puerto struct {
	CodigoPuerto string `xml:"CodigoPuerto,omitempty" json:"CodigoPuerto,omitempty"`
}

type RegistrarEmbarqueRta struct {
	*ResponseAbstract
}

type ResponseAbstract struct {
	*ResultadoEjecucionSerializable
}

type ResultadoEjecucionSerializable struct {
	ListaErrores *ArrayOfDgaMensajeSistemaReducido `xml:"ListaErrores,omitempty" json:"ListaErrores,omitempty"`

	Server string `xml:"Server,omitempty" json:"Server,omitempty"`

	TimeStamp soap.XSDDateTime `xml:"TimeStamp,omitempty" json:"TimeStamp,omitempty"`
}

type ArrayOfDgaMensajeSistemaReducido struct {
	DetalleError []*DgaMensajeSistemaReducido `xml:"DetalleError,omitempty" json:"DetalleError,omitempty"`
}

type DgaMensajeSistemaReducido struct {
	Codigo *int32 `xml:"Codigo,omitempty" json:"Codigo,omitempty"`

	Descripcion string `xml:"Descripcion,omitempty" json:"Descripcion,omitempty"`

	DescripcionAdicional string `xml:"DescripcionAdicional,omitempty" json:"DescripcionAdicional,omitempty"`
}

type RectificarCaratulaRequest struct {
	Caratula *Caratula `xml:"Caratula,omitempty" json:"Caratula,omitempty"`

	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`
}

type RectificarEmbarqueRta struct {
	*ResponseAbstract
}

type AnularCaratulaRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`
}

type AnularEmbarqueRta struct {
	*ResponseAbstract
}

type RegistrarCOEMRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	Coem *Coem `xml:"Coem,omitempty" json:"Coem,omitempty"`
}

type Coem struct {
	ContenedoresConCarga *ArrayOfContenedorCarga `xml:"ContenedoresConCarga,omitempty" json:"ContenedoresConCarga,omitempty"`

	ContenedoresVacios *ArrayOfContenedorVacio `xml:"ContenedoresVacios,omitempty" json:"ContenedoresVacios,omitempty"`

	MercaderiasSueltas *ArrayOfMercaderiaSuelta `xml:"MercaderiasSueltas,omitempty" json:"MercaderiasSueltas,omitempty"`
}

type ArrayOfContenedorCarga struct {
	ContenedorCarga []*ContenedorCarga `xml:"ContenedorCarga,omitempty" json:"ContenedorCarga,omitempty"`
}

type ContenedorCarga struct {
	IdentificadorContenedor string `xml:"IdentificadorContenedor,omitempty" json:"IdentificadorContenedor,omitempty"`

	CuitATA string `xml:"CuitATA,omitempty" json:"CuitATA,omitempty"`

	Tipo string `xml:"Tipo,omitempty" json:"Tipo,omitempty"`

	Peso float64 `xml:"Peso,omitempty" json:"Peso,omitempty"`

	Precintos *ArrayOfPrecinto `xml:"Precintos,omitempty" json:"Precintos,omitempty"`

	Declaraciones *ArrayOfDeclaracion `xml:"Declaraciones,omitempty" json:"Declaraciones,omitempty"`
}

type ArrayOfPrecinto struct {
	Precinto []*Precinto `xml:"Precinto,omitempty" json:"Precinto,omitempty"`
}

type Precinto struct {
	IdentificadorPrecinto string `xml:"IdentificadorPrecinto,omitempty" json:"IdentificadorPrecinto,omitempty"`
}

type ArrayOfDeclaracion struct {
	Declaracion []*Declaracion `xml:"Declaracion,omitempty" json:"Declaracion,omitempty"`
}

type Declaracion struct {
	IdentificadorDeclaracion string `xml:"IdentificadorDeclaracion,omitempty" json:"IdentificadorDeclaracion,omitempty"`
}

type ArrayOfContenedorVacio struct {
	ContenedorVacio []*ContenedorVacio `xml:"ContenedorVacio,omitempty" json:"ContenedorVacio,omitempty"`
}

type ContenedorVacio struct {
	IdentificadorContenedor string `xml:"IdentificadorContenedor,omitempty" json:"IdentificadorContenedor,omitempty"`

	Tipo string `xml:"Tipo,omitempty" json:"Tipo,omitempty"`

	CuitATA string `xml:"CuitATA,omitempty" json:"CuitATA,omitempty"`

	CodigoPais string `xml:"CodigoPais,omitempty" json:"CodigoPais,omitempty"`
}

type ArrayOfMercaderiaSuelta struct {
	MercaderiaSuelta []*MercaderiaSuelta `xml:"MercaderiaSuelta,omitempty" json:"MercaderiaSuelta,omitempty"`
}

type MercaderiaSuelta struct {
	IdentificadorDeclaracion string `xml:"IdentificadorDeclaracion,omitempty" json:"IdentificadorDeclaracion,omitempty"`

	CuitATA string `xml:"CuitATA,omitempty" json:"CuitATA,omitempty"`

	Embalajes *ArrayOfEmbalaje `xml:"Embalajes,omitempty" json:"Embalajes,omitempty"`
}

type ArrayOfEmbalaje struct {
	Embalaje []*Embalaje `xml:"Embalaje,omitempty" json:"Embalaje,omitempty"`
}

type Embalaje struct {
	CodigoEmbalaje string `xml:"CodigoEmbalaje,omitempty" json:"CodigoEmbalaje,omitempty"`

	Peso float64 `xml:"Peso,omitempty" json:"Peso,omitempty"`

	CantidadBultos int32 `xml:"CantidadBultos,omitempty" json:"CantidadBultos,omitempty"`
}

type RectificarCOEMRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	IdentificadorCOEM string `xml:"IdentificadorCOEM,omitempty" json:"IdentificadorCOEM,omitempty"`

	Coem *Coem `xml:"Coem,omitempty" json:"Coem,omitempty"`
}

type AnularCOEMRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	IdentificadorCOEM string `xml:"IdentificadorCOEM,omitempty" json:"IdentificadorCOEM,omitempty"`
}

type CerrarCOEMRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	IdentificadorCOEM string `xml:"IdentificadorCOEM,omitempty" json:"IdentificadorCOEM,omitempty"`
}

type SolicitarCambioBuqueRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	IdentificadorBuque string `xml:"IdentificadorBuque,omitempty" json:"IdentificadorBuque,omitempty"`

	NombreMedioTransporte string `xml:"NombreMedioTransporte,omitempty" json:"NombreMedioTransporte,omitempty"`
}

type SolicitarCambioFechasRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	FechaArribo soap.XSDDateTime `xml:"FechaArribo,omitempty" json:"FechaArribo,omitempty"`

	FechaZarpada soap.XSDDateTime `xml:"FechaZarpada,omitempty" json:"FechaZarpada,omitempty"`

	CodigoMotivo string `xml:"CodigoMotivo,omitempty" json:"CodigoMotivo,omitempty"`

	DescripcionMotivo string `xml:"DescripcionMotivo,omitempty" json:"DescripcionMotivo,omitempty"`
}

type SolicitarCambioLOTRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	CodigoLugarOperativo string `xml:"CodigoLugarOperativo,omitempty" json:"CodigoLugarOperativo,omitempty"`
}

type SolicitarNoABordoRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	IdentificadorCOEM string `xml:"IdentificadorCOEM,omitempty" json:"IdentificadorCOEM,omitempty"`

	CodigoMotivo string `xml:"CodigoMotivo,omitempty" json:"CodigoMotivo,omitempty"`

	DescripcionMotivo string `xml:"DescripcionMotivo,omitempty" json:"DescripcionMotivo,omitempty"`

	IdentificadoresContenedoresVacios *ArrayOfContenedor `xml:"IdentificadoresContenedoresVacios,omitempty" json:"IdentificadoresContenedoresVacios,omitempty"`

	IdentificadoresContenedorCarga *ArrayOfContenedor `xml:"IdentificadoresContenedorCarga,omitempty" json:"IdentificadoresContenedorCarga,omitempty"`

	IdentificadoresDeclaracionesMercaderiaSuelta *ArrayOfDeclaracion `xml:"IdentificadoresDeclaracionesMercaderiaSuelta,omitempty" json:"IdentificadoresDeclaracionesMercaderiaSuelta,omitempty"`
}

type ArrayOfContenedor struct {
	Contenedor []*Contenedor `xml:"Contenedor,omitempty" json:"Contenedor,omitempty"`
}

type Contenedor struct {
	IdentificadorContenedor string `xml:"IdentificadorContenedor,omitempty" json:"IdentificadorContenedor,omitempty"`
}

type SolicitarCierreCargaContoBultoRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	FechaZarpada soap.XSDDateTime `xml:"FechaZarpada,omitempty" json:"FechaZarpada,omitempty"`

	NumeroViaje string `xml:"numeroViaje,omitempty" json:"numeroViaje,omitempty"`

	Declaraciones *ArrayOfDeclaracionCont `xml:"Declaraciones,omitempty" json:"Declaraciones,omitempty"`
}

type ArrayOfDeclaracionCont struct {
	DeclaracionCont []*DeclaracionCont `xml:"DeclaracionCont,omitempty" json:"DeclaracionCont,omitempty"`
}

type DeclaracionCont struct {
	IdentificadorDeclaracion string `xml:"IdentificadorDeclaracion,omitempty" json:"IdentificadorDeclaracion,omitempty"`

	FechaEmbarque soap.XSDDateTime `xml:"FechaEmbarque,omitempty" json:"FechaEmbarque,omitempty"`
}

type SolicitarCierreCargaGranelRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	FechaZarpada soap.XSDDateTime `xml:"FechaZarpada,omitempty" json:"FechaZarpada,omitempty"`

	NumeroViaje string `xml:"numeroViaje,omitempty" json:"numeroViaje,omitempty"`

	Coems *ArrayOfCoemGranel `xml:"Coems,omitempty" json:"Coems,omitempty"`
}

type ArrayOfCoemGranel struct {
	CoemGranel []*CoemGranel `xml:"CoemGranel,omitempty" json:"CoemGranel,omitempty"`
}

type CoemGranel struct {
	IdentificadorCoem string `xml:"IdentificadorCoem,omitempty" json:"IdentificadorCoem,omitempty"`

	Declaraciones *ArrayOfDeclaracionGranel `xml:"Declaraciones,omitempty" json:"Declaraciones,omitempty"`
}

type ArrayOfDeclaracionGranel struct {
	DeclaracionGranel []*DeclaracionGranel `xml:"DeclaracionGranel,omitempty" json:"DeclaracionGranel,omitempty"`
}

type DeclaracionGranel struct {
	IdentificadorDeclaracion string `xml:"IdentificadorDeclaracion,omitempty" json:"IdentificadorDeclaracion,omitempty"`

	FechaEmbarque soap.XSDDateTime `xml:"FechaEmbarque,omitempty" json:"FechaEmbarque,omitempty"`

	IdentificadorCierreCumplido string `xml:"IdentificadorCierreCumplido,omitempty" json:"IdentificadorCierreCumplido,omitempty"`

	Items *ArrayOfItem `xml:"Items,omitempty" json:"Items,omitempty"`
}

type ArrayOfItem struct {
	Item []*Item `xml:"Item,omitempty" json:"Item,omitempty"`
}

type Item struct {
	NumeroItem int32 `xml:"numeroItem,omitempty" json:"numeroItem,omitempty"`

	CantidadReal float64 `xml:"cantidadReal,omitempty" json:"cantidadReal,omitempty"`
}

type SolicitarAnulacionCOEMRequest struct {
	IdentificadorCaratula string `xml:"IdentificadorCaratula,omitempty" json:"IdentificadorCaratula,omitempty"`

	IdentificadorCOEM string `xml:"IdentificadorCOEM,omitempty" json:"IdentificadorCOEM,omitempty"`
}

type ResultadoEjecucionDummy struct {
	AppServer string `xml:"AppServer,omitempty" json:"AppServer,omitempty"`

	DbServer string `xml:"DbServer,omitempty" json:"DbServer,omitempty"`

	AuthServer string `xml:"AuthServer,omitempty" json:"AuthServer,omitempty"`
}

type WgescomunicacionembarqueSoap interface {

	/* Registrar Carátula */
	RegistrarCaratula(request *RegistrarCaratula) (*RegistrarCaratulaResponse, error)

	RegistrarCaratulaContext(ctx context.Context, request *RegistrarCaratula) (*RegistrarCaratulaResponse, error)

	/* Rectificar Carátula */
	RectificarCaratula(request *RectificarCaratula) (*RectificarCaratulaResponse, error)

	RectificarCaratulaContext(ctx context.Context, request *RectificarCaratula) (*RectificarCaratulaResponse, error)

	/* Anular Carátula */
	AnularCaratula(request *AnularCaratula) (*AnularCaratulaResponse, error)

	AnularCaratulaContext(ctx context.Context, request *AnularCaratula) (*AnularCaratulaResponse, error)

	/* Registrar Comunicación de Embarque */
	RegistrarCOEM(request *RegistrarCOEM) (*RegistrarCOEMResponse, error)

	RegistrarCOEMContext(ctx context.Context, request *RegistrarCOEM) (*RegistrarCOEMResponse, error)

	/* Rectificar Comunicación de Embarque */
	RectificarCOEM(request *RectificarCOEM) (*RectificarCOEMResponse, error)

	RectificarCOEMContext(ctx context.Context, request *RectificarCOEM) (*RectificarCOEMResponse, error)

	/* Anular una Comunicación de Embarque */
	AnularCOEM(request *AnularCOEM) (*AnularCOEMResponse, error)

	AnularCOEMContext(ctx context.Context, request *AnularCOEM) (*AnularCOEMResponse, error)

	/* Cerrar Comunicación de Embarque */
	CerrarCOEM(request *CerrarCOEM) (*CerrarCOEMResponse, error)

	CerrarCOEMContext(ctx context.Context, request *CerrarCOEM) (*CerrarCOEMResponse, error)

	/* Solicitar Cambio de Buque */
	SolicitarCambioBuque(request *SolicitarCambioBuque) (*SolicitarCambioBuqueResponse, error)

	SolicitarCambioBuqueContext(ctx context.Context, request *SolicitarCambioBuque) (*SolicitarCambioBuqueResponse, error)

	/* Solicitar Cambio de Fecha/s */
	SolicitarCambioFechas(request *SolicitarCambioFechas) (*SolicitarCambioFechasResponse, error)

	SolicitarCambioFechasContext(ctx context.Context, request *SolicitarCambioFechas) (*SolicitarCambioFechasResponse, error)

	/* Solicitar Cambio de Lugar Operativo */
	SolicitarCambioLOT(request *SolicitarCambioLOT) (*SolicitarCambioLOTResponse, error)

	SolicitarCambioLOTContext(ctx context.Context, request *SolicitarCambioLOT) (*SolicitarCambioLOTResponse, error)

	/* Solicitud de No Abordar */
	SolicitarNoABordo(request *SolicitarNoABordo) (*SolicitarNoABordoResponse, error)

	SolicitarNoABordoContext(ctx context.Context, request *SolicitarNoABordo) (*SolicitarNoABordoResponse, error)

	/* Solicitud de Cierre de Carga Contenedores o Bultos Sueltos */
	SolicitarCierreCargaContoBulto(request *SolicitarCierreCargaContoBulto) (*SolicitarCierreCargaContoBultoResponse, error)

	SolicitarCierreCargaContoBultoContext(ctx context.Context, request *SolicitarCierreCargaContoBulto) (*SolicitarCierreCargaContoBultoResponse, error)

	/* Solicitud de Cierre de Carga Granel */
	SolicitarCierreCargaGranel(request *SolicitarCierreCargaGranel) (*SolicitarCierreCargaGranelResponse, error)

	SolicitarCierreCargaGranelContext(ctx context.Context, request *SolicitarCierreCargaGranel) (*SolicitarCierreCargaGranelResponse, error)

	/* Solicitar Anulación de Comunicación de Embarque */
	SolicitarAnulacionCOEM(request *SolicitarAnulacionCOEM) (*SolicitarAnulacionCOEMResponse, error)

	SolicitarAnulacionCOEMContext(ctx context.Context, request *SolicitarAnulacionCOEM) (*SolicitarAnulacionCOEMResponse, error)

	Dummy(request *Dummy) (*DummyResponse, error)

	DummyContext(ctx context.Context, request *Dummy) (*DummyResponse, error)
}

type wgescomunicacionembarqueSoap struct {
	client *soap.Client
}

func NewWgescomunicacionembarqueSoap(client *soap.Client) WgescomunicacionembarqueSoap {
	return &wgescomunicacionembarqueSoap{
		client: client,
	}
}

func (service *wgescomunicacionembarqueSoap) RegistrarCaratulaContext(ctx context.Context, request *RegistrarCaratula) (*RegistrarCaratulaResponse, error) {
	response := new(RegistrarCaratulaResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/RegistrarCaratula", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) RegistrarCaratula(request *RegistrarCaratula) (*RegistrarCaratulaResponse, error) {
	return service.RegistrarCaratulaContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) RectificarCaratulaContext(ctx context.Context, request *RectificarCaratula) (*RectificarCaratulaResponse, error) {
	response := new(RectificarCaratulaResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/RectificarCaratula", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) RectificarCaratula(request *RectificarCaratula) (*RectificarCaratulaResponse, error) {
	return service.RectificarCaratulaContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) AnularCaratulaContext(ctx context.Context, request *AnularCaratula) (*AnularCaratulaResponse, error) {
	response := new(AnularCaratulaResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/AnularCaratula", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) AnularCaratula(request *AnularCaratula) (*AnularCaratulaResponse, error) {
	return service.AnularCaratulaContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) RegistrarCOEMContext(ctx context.Context, request *RegistrarCOEM) (*RegistrarCOEMResponse, error) {
	response := new(RegistrarCOEMResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/RegistrarCOEM", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) RegistrarCOEM(request *RegistrarCOEM) (*RegistrarCOEMResponse, error) {
	return service.RegistrarCOEMContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) RectificarCOEMContext(ctx context.Context, request *RectificarCOEM) (*RectificarCOEMResponse, error) {
	response := new(RectificarCOEMResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/RectificarCOEM", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) RectificarCOEM(request *RectificarCOEM) (*RectificarCOEMResponse, error) {
	return service.RectificarCOEMContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) AnularCOEMContext(ctx context.Context, request *AnularCOEM) (*AnularCOEMResponse, error) {
	response := new(AnularCOEMResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/AnularCOEM", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) AnularCOEM(request *AnularCOEM) (*AnularCOEMResponse, error) {
	return service.AnularCOEMContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) CerrarCOEMContext(ctx context.Context, request *CerrarCOEM) (*CerrarCOEMResponse, error) {
	response := new(CerrarCOEMResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/CerrarCOEM", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) CerrarCOEM(request *CerrarCOEM) (*CerrarCOEMResponse, error) {
	return service.CerrarCOEMContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) SolicitarCambioBuqueContext(ctx context.Context, request *SolicitarCambioBuque) (*SolicitarCambioBuqueResponse, error) {
	response := new(SolicitarCambioBuqueResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/SolicitarCambioBuque", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) SolicitarCambioBuque(request *SolicitarCambioBuque) (*SolicitarCambioBuqueResponse, error) {
	return service.SolicitarCambioBuqueContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) SolicitarCambioFechasContext(ctx context.Context, request *SolicitarCambioFechas) (*SolicitarCambioFechasResponse, error) {
	response := new(SolicitarCambioFechasResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/SolicitarCambioFechas", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) SolicitarCambioFechas(request *SolicitarCambioFechas) (*SolicitarCambioFechasResponse, error) {
	return service.SolicitarCambioFechasContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) SolicitarCambioLOTContext(ctx context.Context, request *SolicitarCambioLOT) (*SolicitarCambioLOTResponse, error) {
	response := new(SolicitarCambioLOTResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/SolicitarCambioLOT", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) SolicitarCambioLOT(request *SolicitarCambioLOT) (*SolicitarCambioLOTResponse, error) {
	return service.SolicitarCambioLOTContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) SolicitarNoABordoContext(ctx context.Context, request *SolicitarNoABordo) (*SolicitarNoABordoResponse, error) {
	response := new(SolicitarNoABordoResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/SolicitarNoABordo", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) SolicitarNoABordo(request *SolicitarNoABordo) (*SolicitarNoABordoResponse, error) {
	return service.SolicitarNoABordoContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) SolicitarCierreCargaContoBultoContext(ctx context.Context, request *SolicitarCierreCargaContoBulto) (*SolicitarCierreCargaContoBultoResponse, error) {
	response := new(SolicitarCierreCargaContoBultoResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/SolicitarCierreCargaContoBulto", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) SolicitarCierreCargaContoBulto(request *SolicitarCierreCargaContoBulto) (*SolicitarCierreCargaContoBultoResponse, error) {
	return service.SolicitarCierreCargaContoBultoContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) SolicitarCierreCargaGranelContext(ctx context.Context, request *SolicitarCierreCargaGranel) (*SolicitarCierreCargaGranelResponse, error) {
	response := new(SolicitarCierreCargaGranelResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/SolicitarCierreCargaGranel", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) SolicitarCierreCargaGranel(request *SolicitarCierreCargaGranel) (*SolicitarCierreCargaGranelResponse, error) {
	return service.SolicitarCierreCargaGranelContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) SolicitarAnulacionCOEMContext(ctx context.Context, request *SolicitarAnulacionCOEM) (*SolicitarAnulacionCOEMResponse, error) {
	response := new(SolicitarAnulacionCOEMResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/SolicitarAnulacionCOEM", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) SolicitarAnulacionCOEM(request *SolicitarAnulacionCOEM) (*SolicitarAnulacionCOEMResponse, error) {
	return service.SolicitarAnulacionCOEMContext(
		context.Background(),
		request,
	)
}

func (service *wgescomunicacionembarqueSoap) DummyContext(ctx context.Context, request *Dummy) (*DummyResponse, error) {
	response := new(DummyResponse)
	err := service.client.CallContext(ctx, "Ar.Gob.Afip.Dga.wgescomunicacionembarque/Dummy", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wgescomunicacionembarqueSoap) Dummy(request *Dummy) (*DummyResponse, error) {
	return service.DummyContext(
		context.Background(),
		request,
	)
}
